### ISSUE TITLE
Pass Rundeck options through to playbooks

### ISSUE THREAD

**Issue by colebrumley** [rundeck-plugins/ansible-plugin#10]
Not sure if this is a duplicate of #7 or not, but there needs to be a way to pass a Rundeck job's options through to Ansible. Right now I'm kinda stuck using a separate playbook for each permutation of a step that I'd normally parameterize, like deployments to different envs.

It'd be awesome if the playbook step automagically passed the job's options through as `--extra-vars`, but just making them available in the environment would be fine too.

**Comment by rilindo** [comment]
I would like to see that too. Rundeck is able to pull node metadata from AWS faster than Ansible, so passing the rundeck hostname variable to Ansible would be very helpful.

**Comment by frozenice** [comment]
Sounds like a good idea. I'll investigate how to best implement this.

@rilindo it already does this, see https://github.com/Batix/rundeck-ansible-plugin/issues/8#issuecomment-202750127

**Comment by suivethefirst** [comment]
I agree this would be nice to have options passed through explicitly.

In the meantime there's a workaround of sorts. If you configure a job with two options, for example, test1 and test2. Then in your workflow define your playbook extra arguments as:

`-e "test1=${option.test1} test2=${option.test2}"`

That way you get the values of the options set to those variable names in the arguments to ansible-playbook.

**Comment by yassineazzouz** [comment]
Hi @colebrumley ,

Please check release 2.0.1, rundeck options are now available as environment variables for the ansible process.

Thanks,

**Comment by brokenjacobs** [comment]
the extra variables are pased from rundeck using the @file notation for ansible-playbook. This means you can use ansible's yaml syntax in the definition of the job, and convert the options there like this:
ansible_var1: ${option.rundeck_var1}
You can even use jinja filters there like this:
vm_mb_ramsize: "{{ ${option.vm_gb_ramsize}|int * 1024}}"

I couldn't find this in the docs, but it works great. I hope its helpful!

You place the settings in the **Extra Variables** section of your job definition.

**Comment by DerekTBrown** [comment]
This should be more clear now that syntax highlighting is enabled.  Needs to be added to documentation.

**Comment by broferek** [comment]
Is there any way to get a Rundeck multi valued option passed as an Ansible list?

For the moment, it seems that the Rundeck is typed as a string and I don't see any way to convert it to a list in the extra_vars section.

**Comment by mnasiadka** [comment]
Is there a way to pass project global variables to Ansible?

**Comment by mcassaniti** [comment]
@broferek Can you please raise a separate issue for passing a Rundeck list into Ansible?
@mnasiadka Can you please raise a separate issue for passing Rundeck global variables to Ansible?

**Comment by mcassaniti** [comment]
Issue has gone stale. Closing. If you need further assistance then please post again.
