### ISSUE TITLE
Support Ansible Dynamic Inventory

### ISSUE THREAD

**Issue by ko-christ** [rundeck-plugins/ansible-plugin#101]
> ansible-inventory - Specifies the ansible inventory to use, can defined a global inventory file at the project > level without requiring setting the same variable for each job. (default /etc/ansible/hosts)

Supporting dynamic inventory (eg `inventory.sh --list`) as well, would be a nice enhancement.

http://docs.ansible.com/ansible/intro_dynamic_inventory.html
http://docs.ansible.com/ansible/dev_guide/developing_inventory.html

**Comment by shadycuz** [comment]
I only use dynamic inventories.

**Comment by brokenjacobs** [comment]
The plugin already supports dynamic inventories, as well as ansible dynamic inventory scripts in directories.

**Comment by shadycuz** [comment]
@brokenjacobs Maybe that feature is newer or I didn't configure it right. I ended up ditching the plugin and just running all my playbooks from rundeck as commands on a localhost. Works great for me just like that.

**Comment by pmioulet** [comment]
You can run a playbook with a dynamic inventory but the nodes section of rundeck don't seem to get filled with the nodes. I set the property at the project level, I can see that it is used in my jobs but I don't see any of my nodes in rundeck UI.
Am I missing something, should I set the property else where? It's rather annoying as the limit is only targeting my rundeck server.

**Comment by shadycuz** [comment]
@pmioulet Same issue I had, no inventory.

**Comment by brokenjacobs** [comment]
I had to configure the inventory at the project level using the settings described on the project page.
Under project configuration -> Edit configuration file (not simple configuration). I added the following:
```
ansible-become-method=sudo
ansible-become=true
ansible-ssh-auth-type=privateKey
ansible-ssh-keypath=/var/lib/rundeck/.ssh/id_rsa
ansible-ssh-user=ansible-ipa
project.ansible-become-method=sudo
project.ansible-become=true
project.ansible-executable=/bin/bash
project.ansible-inventory=/var/lib/rundeck/ci-ansible/inventories/freeipa
project.ansible-ssh-auth-type=privateKey
project.ansible-ssh-user=ansible-ipa
```

It didn't work until I added the inventory path to the project itself in the config file.

Now as to its utility... based on the localhost stuff I described in another ticket, maybe you are better off not using the plugin. I'm not sure.

**Comment by frozenice** [comment]
@brokenjacobs I saw that e.g. the Node Executor plugin doesn't pull config options from the resource model source. This is because the inventory path etc. is defined as a property of the resource model source config, which is some levels deeper than the project config.
I'm thinking about storing a reference to the source which was used to create a node, on the node, if there is none already. This would also enable multiple inventories per project, I guess.

**Comment by pmioulet** [comment]
Issue #102 you mean? I faced the same problem and saw that ticket. I kind of suspected that if I got my inventory populated I could select other nodes which might also address that.

I only created the property project.ansible-inventory which allowed jobs to retrieve the hosts through my dynamic inventory but the node section was not populated. I'll look around to see if I can spot an error in the logs.

**Comment by brokenjacobs** [comment]
That's the one.

**Comment by pmioulet** [comment]
My bad, for futur reference, I had misconfigured the "Ansible Resource Model". With this plugin properly configured in the project I totally got the inventory working with a dynamic script.

**Comment by javierurien** [comment]
I feel like a dumb here, but how is it that you get to use dynamic inventory with batix?
I have `/var/lib/rundeck/ansible/hosts/` and on that path I have 3 inventory files: `hosts, inventory.sh, vmware_inventory.py` the last two executables.
If I configure:

-  `ansible inventory File path: /var/lib/rundeck/ansible/hosts/`: I get no hosts
-  `ansible inventory File path: /var/lib/rundeck/ansible/hosts/inventory.sh`: I get no hosts
-  `ansible inventory File path: /var/lib/rundeck/ansible/hosts/hosts`: I get only static hosts

I am missing something?

Thanks in advance.

Best Regards

**Comment by tsgan** [comment]
Can someone show me how to configure rundeck with ansible dynamic inventory? I have dynamic inventory script and it is working. However when I set ansible inventory File path: /usr/local/rundeck/inventory.py it is not working, I don't see Nodes in web GUI.

**Comment by mcassaniti** [comment]
Please make sure that the same user Ansible is running as can execute your dynamic inventory file. The Rundeck Ansible inventory works by running something like:
```ansible-playbook --inventory <path-to-inventory-script-or-file> gather-hosts.yml```

The playbook `gather-hosts.yml` can be found at https://github.com/Batix/rundeck-ansible-plugin/tree/master/src/main/resources

You're welcome to try manually and determine if there are problems with your setup.
