### ISSUE TITLE
Issue handling hosts file with children as hosts variable passed via extra variable

### ISSUE THREAD

**Issue by stefanponik** [rundeck-plugins/ansible-plugin#106]
Hi Guys, 

I think there is a bug with extra variable passing hosts in to playbook and host name is name that is in hosts file with children option. I am not a software engineer so dont take my word for it. 

Playbook for testing with hosts set to variable. 
`rundeck@ubuntu1:~/ansible/playbooks$ cat df_h_test.yml
- hosts: "{{ hosts }}"
  become: true
  tasks:
  - name: Show space
    shell: df -h
    register: df_var`

My test host file:
`[example1]
172.16.178.199 ansible_user=rundeck

[example2]
172.16.178.208 ansible_user=rundeck

[ubuntu5]
172.16.178.209

[funky:children]
example1
example2`

Using CLI on same server to test: 
**ansible-playbook df_h_test.yml -i /var/lib/rundeck/ansible/hosts_files/test_project1 -l "172.16.178.199,172.16.178.208"  --extra-vars="hosts=funky"**

Output: 
`PLAY [funky] *******************************************************************

TASK [setup] *******************************************************************
ok: [172.16.178.199]
ok: [172.16.178.208]

TASK [Show space] **************************************************************
changed: [172.16.178.199]
changed: [172.16.178.208]

PLAY RECAP *********************************************************************
172.16.178.199             : ok=2    changed=1    unreachable=0    failed=0
172.16.178.208             : ok=2    changed=1    unreachable=0    failed=0`

In GUI once you using rundeck plugin. 

In workflow step you create same: 

![snip20170403_1](https://cloud.githubusercontent.com/assets/20069019/24610179/7ff1e8a2-1875-11e7-8d5e-26d8c5753f53.png)

Define tags: 
![snip20170403_3](https://cloud.githubusercontent.com/assets/20069019/24610186/8a97a49a-1875-11e7-9709-66588443cd21.png)

Execute that as job and it complete successfully but without any work done: Debug level output. 

![snip20170403_4](https://cloud.githubusercontent.com/assets/20069019/24610406/51662aba-1876-11e7-934f-f9d41d55221b.png)

Workaround for this is to set hosts and keep tag as it is. 

![snip20170403_5](https://cloud.githubusercontent.com/assets/20069019/24610582/078190c8-1877-11e7-9b6b-79e645698f04.png)

Use same tag: 
![snip20170403_3](https://cloud.githubusercontent.com/assets/20069019/24610593/10e17908-1877-11e7-93af-38159a45fa42.png)

Output: 
![snip20170403_6](https://cloud.githubusercontent.com/assets/20069019/24610606/196acf98-1877-11e7-919b-76a9f476fda2.png)

Maybe I am doing something wrong but I dont think as it works fine if instead of funky I supply example1 for tag and extra variable.

**Comment by DerekTBrown** [comment]
This truly is funky.  I don't see the `--inventory-file=` flag being set in procArgs, which it should be in order for this to work.  Can you double check the configuration of the resource?

This issue is kinda old- so I am closing for now.  Feel free to reopen if need be.
