### ISSUE TITLE
Playbooks fail - 'Error configuring Ansible runner'

### ISSUE THREAD

**Issue by mkempster22** [rundeck-plugins/ansible-plugin#107]
I have Rundeck setup on a CentOS7 Server,
Currently its just a copy of a production Ansible server we have with a few simple playbooks, whenever I try run a playbook regardless of its contents it instantly fails, this is the output from debug mode execution:

TL:DR of output:
08:00:34			Error configuring Ansible runner.
08:00:34			Execution failed: 51 in project Ansible: [Workflow result: , step failures {1=ParseArgumentsError: Error configuring Ansible runner.}, flow control: Continue, status: failed]

[Output.txt](https://github.com/Batix/rundeck-ansible-plugin/files/915810/Output.txt)

**Comment by DerekTBrown** [comment]
This looks like the root cause of the error in your output:

```
Caused by: com.dtolabs.rundeck.core.plugins.configuration.ConfigurationException: Failed to read the ssh private key from path /root/.ssh/id_dsa: /root/.ssh/id_dsa
```

This is because Rundeck executes playbooks from the `rundeck` user, which doesn't necessarily have permissions to access `/root/`.  You need to modify your SSH configuration.  Reopen if the problem persists.
