### ISSUE TITLE
SSH password prompt during save of project's configuration.

### ISSUE THREAD

**Issue by hashedvalue** [rundeck-plugins/ansible-plugin#110]
Hi.

I configured ansible plugin according to https://github.com/Batix/rundeck-ansible-plugin#installation and when I try to save the project every time I get in STDOUT/STDIN of rundeck process

SSH password:

prompt. It corresponds to the user set for "Ansible Resource Model Source" but in below fields I have:

SSH Authentication: password
SSH User: appUser
SSH Password: appPassword

This is quite a pain since every time I am modifying the configuration or performing node lookup I have to type the password in STDIN of rundeck process.

I am using:
debian jessy docker container
rundeck-2.7.3-1-GA.deb package
ansible 2.3.0.0

and can invoke ansible directly from the container shell with ok result:

ansible all -i /var/lib/rundeck/ansible/inv/test.inv -u appUser -k -m ping

Can someone help?

**Comment by DerekTBrown** [comment]
Can you post a copy of your project configuration?

**Comment by DerekTBrown** [comment]
Closing because this is stale.  Reopen if this is something you are still having a problem with.
