### ISSUE TITLE
Support of ansible-container

### ISSUE THREAD

**Issue by tipruzs** [rundeck-plugins/ansible-plugin#114]
Is it possible to support [ansible-container](https://www.ansible.com/ansible-container) in the future?

**Comment by DerekTBrown** [comment]
All of the functionality of ansible-container is implemented in other ways.

For managing Docker containers, use the native Ansible Module:
http://docs.ansible.com/ansible/latest/docker_container_module.html#docker-container

For managing OpenShift clusters:
https://github.com/ansible/ansible-container

If for some reason one of those two packages dont contain what you need, you can use Ansible to install Ansible-Container, and then run the commands using the shell module.

I don't see this as an active issue for the plugin, so I am closing.
