### ISSUE TITLE
Error with failed jobs | No matched nodes: MultiNodeSelector{nodenames=[ansible.somedomain.local]}

### ISSUE THREAD

**Issue by ronator** [rundeck-plugins/ansible-plugin#115]
Hi,

I have a problem with rundeck running on an ansible controller with this nice ansible-plugin. I checked if such an error was already reported and I asked in IRC #rundeck, but I could not find any solution. I thought this may be a config error, but I am unsure about that.

### Environment, versions (OS, Ansible, Rundeck, Plugin)

OS Ubuntu 16.04.2 (kernel 4.4.0-79)
Ansible 2.1.1.0
Rundeck build 2.8.2-1
Plugin ansible-rundeck 2.0.2

Java jvm implementationVersion 25.131-b11
name OpenJDK 64-Bit Server VM
vendor Oracle Corporation
version 1.8.0_131

### How to reproduce

I installed rundeck on a Ubuntu server, added the ansible-plugin and added one ssh key and one sudo pass in the global config, then configured a project and set the "Resource Model Source" to "Ansible Resource Model Source". I can see that it reads my inventory file and that it does basic fact gathering. I am not using any more plugins; I only need Ansible to integrate with Rundeck. My Ansible host is reachable with DNS.

I cannot see ANY node in rundeck webui, though (0 nodes). I was told in IRC, that this is normal behaviour: "The node count is not working because the plugin is a workflow step and not a node step (like it was previously)".

Then I created a job for that project in rundeck webui that only calls "uptime". When I try to run it, it fails immediately and service.log shows this output:
```
INFO  ScheduledExecutionService: scheduling immediate job run: TEMP:admin:1:3
WARN  FrameworkService: Empty node list
WARN  FrameworkService: Empty node list
ERROR ExecutionUtilService: Execution failed: 3 in project ansible-test-01: No matched nodes: MultiNodeSelector{nodenames=[ansible.somedomain.local]}
Using /etc/ansible/ansible.cfg as config file
/usr/lib/python2.7/getpass.py:83: GetPassWarning: Can not control echo on the terminal.
  passwd = fallback_getpass(prompt, stream)
Warning: Password input may be echoed.
SUDO password:
 
PLAY [all] *********************************************************************
 
TASK [setup] *******************************************************************
ok: [host1]
ok: [host2]
...
```

This can be just a configuration mistake but since I couldn't find help in any search machine or even in IRC channel, I was hoping that this report may solve my issue as I do not know what the problem is, though the error messages sounds quite informative.

Any help or suggestions are appreciated. I beg your pardon if I caused any unnecessary noise.

Best wishes

**Comment by MAS150MD200** [comment]
I have the same issue.

**Comment by DerekTBrown** [comment]
The answer you got on IRC was half right.  You should see nodes under the "nodes" section of the WebUI, but upon successful completion of a job, it will not register as having completed on any of the nodes, but will still show success/failure.  This is by nature of the design of the plugin as a workflow step.  If you aren't seeing nodes in the "nodes" view- reopen, because that is an actual issue.

**Comment by ronator** [comment]
Hi,

sorry, I was 'off' for a while.

Well, I wanted to pimp my ansible host with a (free) webui so I came across rundeck and the ansible plugin. Hence, I have no rundeck experience at all. I guess there could be problems that might go beyond rundeck+ansible-plugin itsself pointing to my certain ansible setup instead. Maybe it is just a local user permission problem since I do ansible mostly as root and that may not work so well with the rundeck user. 

I appreciate you left this open as a question for some weeks. Unfortunately, I had to focus on other topics and I can't promise to investigate my local rundeck+ansible configuration problem (which is seems to be) any soon again. So please feel free to close this issue.

That being said, I truly love the idea of rundeck+ansible so I will definitely come back to this awesome project.
