### ISSUE TITLE
In Memory Cache with Add-Host seems not to work properly

### ISSUE THREAD

**Issue by BigBen8** [rundeck-plugins/ansible-plugin#116]
Hi,

i run a script that launchs ec2 instances and then do some Actions like joining a Domain.
therefore I used the in Memory Cache of the ansible module add_host. The playbook works fine started via Ansible (CLI-Command), but fail if started via Rundeck.

Script looks like:

- hosts: all
  connection: local
  gather_facts: False
  vars:
    keypair: somekey
    instance_type: t2.micro
    security_group: somesg
    image: someami
    region: someregion
  tasks:
  - ec2:
     key_name: "{{ keypair }}"
     group: "{{ security_group }}"
     instance_type: "{{ instance_type }}"
     image: "{{ image }}"
     wait: true
     region: "{{ region }}"
     instance_tags:
       Name: Tag1
       Function: Tag2...
     vpc_subnet_id: somesubnet
     assign_public_ip: no
     volumes:
          - device_name: /dev/sda1
            volume_type: gp2
            volume_size: 65
    register: ec2

  - add_host:
       hostname: "{{ item.private_ip }}"
       groupname: windows
    with_items: "{{ ec2.instances }}"

  - wait_for:
        port: 3389
        host: "{{ item.private_ip }}"
        delay: 60
        timeout: 1200
        state: started
    with_items: "{{ ec2.instances }}"

- hosts: windows
  connection: local
  gather_facts: False
  tasks:
   - win_domain_membership:
       dns_domain_name: somedomain
       domain_admin_user: someuser
       domain_admin_password: somepasswd
       domain_ou_path: someou
       state: domain
     register: domain_state

   - win_reboot:

I Trigger the script in Rundeck like:
![unbenannt](https://user-images.githubusercontent.com/28532554/27324834-ba44f22e-55a6-11e7-80f6-f7d95d0bbe88.PNG)

add_host in script seems to work:

![add_host](https://user-images.githubusercontent.com/28532554/27325858-0df9ac0e-55aa-11e7-93eb-314c1290a37f.PNG)

in my log i get the following:

![error](https://user-images.githubusercontent.com/28532554/27325871-14300636-55aa-11e7-8853-2bd263a57a31.PNG)

Any help on this would be great. Thanks in advance!

**Comment by DerekTBrown** [comment]
@BigBen8 Not sure what is going on here, but would need more information. It is generally a bad idea to use add_host without a file.  I would suggest splitting this into two playbooks: one which generates the EC2 Hosts and writes this information to a file, and a second which uses this to call hosts.  This way you can re-run jobs if they fail, and have a persistent copy.

**Comment by DerekTBrown** [comment]
I just ran into this issue myself.  The problem is that Rundeck is sending the limit parameter:

https://github.com/Batix/rundeck-ansible-plugin/issues/116
