### ISSUE TITLE
ansible and rundeck separate hosts

### ISSUE THREAD

**Issue by Daryes** [rundeck-plugins/ansible-plugin#120]
using ansible-plugin-2.0.2.jar

Hello,
I've searched for a while, but I'm not seeing any option related to this situation : 
- server A : ansible master
- server B : rundeck

The rundeck user is able to ssh to ansible@ansible_master without problem, but as there are options in the node executor, the ansible resource model source in the project configuration panel, doesn't provide any clear possibility to handle this situation. And the "SSH connection" section doesn't seems to be related to this.

Is it mandatory to have both ansible and rundeck installed on the same server, or did I miss something ?

**Comment by DerekTBrown** [comment]
@Daryes that is correct- this module executes ansible commands locally, not on a remote system.  If this is a feature you need in the long run, feel free to submit a PR!
