### ISSUE TITLE
Imports nodes from Ansible's inventory is very slow

### ISSUE THREAD

**Issue by FANGXIANGQUAN** [rundeck-plugins/ansible-plugin#121]
I use the ansible resource model, but from the hosts file ansible node information very slow, excuse me what method to solve?

**Comment by rangsan** [comment]
From my view ,if the inventory file is big like 1000 servers inside with huge group_var. Ansible itself is very slow to gathering node.

**Comment by Caidran** [comment]
If you tail the /var/log/rundeck/service.log once you start adding the nodes you will see output just like you would via Ansible as it gathers facts from each node, this will generally take just as long as Ansible would to gather facts from all hosts in your list.

**Comment by DerekTBrown** [comment]
@Caidran is correct- this is more of a limitation of Ansible than the plugin.  You can easily increase the cache duration in settings to accommodate for this, so that it only runs a limited number of times.
