### ISSUE TITLE
Run ansible playbook with rundeck with different SU_PROMPT_LOCALIZATIONS

### ISSUE THREAD

**Issue by Stephane80000** [rundeck-plugins/ansible-plugin#123]
Hi,
I use become method for privilege escalation.
On my server I use sesu instead of su so I have modify ansible.cfg and play_context.py.
It work with ansible command line but doesn't with rundeck.

**My environment:**
python2.7
ansible-plugin-2.0.2.jar
rundeck-launcher-2.8.4.jar
ansible 2.2.0.0

**ansible.cfg :**
su_exe = "/usr/bin/sesu"
su_flags = -

**/usr/lib/python2.7/site-packages/ansible/playbook/play_context.py**
to_bytes('Please enter your password'),

**Ansible commandline**
ansible-playbook myplaybook.yml -i hosts -vvv --ask-pass --ask-become-pass

**Error on rundeck**
fatal: [s00vl9973701]: FAILED! => {
"failed": true,
"msg": "Timeout (32s) waiting for privilege escalation prompt: "

**myplaybook.yml**
- name: apply common configuration to all nodes
  hosts: all
  remote_user: lxxxxxx
  become: true
  become_user: root
  become_method: su

  roles:
    - common

**Comment by Stephane80000** [comment]
Hi,
There is a problem with an option in Rundeck.
In the Job Workflow, normaly I don't have to select "Use become previlege escalation" if I want to use escalation with password but it doesn't work.
So I try with this option "Use become previlege escalation" and it's working.
Maybe there is bug because I don't have this case when I defined a "Ansible Resource Model Source" in my Project.

**Comment by DerekTBrown** [comment]
I am kinda unclear on what error you are getting.  Seems like you got it working with "use become privilege escalation".  Can you reopen and clarify?
