### ISSUE TITLE
Empty node list - Error configuring Ansible runner

### ISSUE THREAD

**Issue by djordje-petrovic** [rundeck-plugins/ansible-plugin#126]
Hi.
All the requirements from the main page are met.
Still the plugin won't pass the nodes from Ansible inventory.
I've specified another user to run ansible (not default rundeck).
But both this user and 'rundeck' can run Ansible.
Any ideas? Thanks.

Relevant log excerpt:

> WARN  LoggingResourceModelSourceCache: [ResourceModelSource: 1.source (com.batix.rundeck.plugins.AnsibleResourceModelSourceFactory), project: ansible_test_01] Returning cached model data
> INFO  ScheduledExecutionService: scheduling immediate job run: TEMP:admin:2:21
> WARN  FrameworkService: Empty node list
> WARN  FrameworkService: Empty node list
> ERROR ExecutionUtilService: Execution failed: 21 in project ansible_test_01: [Workflow result: , step failures: {1=ParseArgumentsError: Error configuring Ansible runner.}, flow control: Continue, status: failed]
> 

Project config file:

> ansible-become-method=su
> ansible-ssh-auth-type=privateKey
> ansible-ssh-keypath=/home/ansi/.ssh/id_rsa
> ansible-ssh-user=ansi
> project.ansible-become-method=su
> project.ansible-executable=/bin/bash
> project.ansible-ssh-auth-type=privateKey
> project.ansible-ssh-keypath=/home/ansi/.ssh/id_rsa
> project.ansible-ssh-user=ansi
> project.description=
> project.disable.executions=false
> project.disable.schedule=false
> project.jobs.gui.groupExpandLevel=1
> project.name=ansible_test_01
> project.nodeCache.delay=30
> project.nodeCache.enabled=true
> project.ssh-authentication=privateKey
> project.ssh-keypath=/var/lib/rundeck/.ssh/id_rsa
> resources.source.1.config.ansible-become=false
> resources.source.1.config.ansible-gather-facts=true
> resources.source.1.config.ansible-ignore-errors=true
> resources.source.1.config.ansible-inventory=/home/ansi/inventories/test01
> resources.source.1.config.ansible-ssh-auth-type=privateKey
> resources.source.1.config.ansible-ssh-keypath=/home/ansi/.ssh/id_rsa
> resources.source.1.config.ansible-ssh-user=ansi
> resources.source.1.type=com.batix.rundeck.plugins.AnsibleResourceModelSourceFactory
> service.FileCopier.default.provider=com.batix.rundeck.plugins.AnsibleFileCopier
> service.NodeExecutor.default.provider=com.batix.rundeck.plugins.AnsibleNodeExecutor
>

**Comment by djordje-petrovic** [comment]
Ok. After some debugging I've solved this problem. It was related to ssh key permissions. However I'm now encountering this error:

> Using /etc/ansible/ansible.cfg as config file
> ERROR! failed to combine variables, expected dicts but got a 'dict' and a 'AnsibleUnicode': 
> {}
> "--limit 'misc'"
> ERROR: Ansible execution returned with non zero code.
> Execution failed: 28 in project ansible_test_01: [Workflow result: , step failures: {1=AnsibleNonZero: ERROR: Ansible execution returned with non zero code.}, flow control: Continue, status: failed]

Also how do I supply vault password? Adding --ask-vault-pass fails.

**Comment by djordje-petrovic** [comment]
Figured this out too. Now I can run playbooks from Rundeck.
However still no nodes showing up. It's because Ansible Resource Model Source fails to decrypt vault files.
Each time I hit 'Save' on ARMS this error is being generated:
> ERROR! Decryption failed on /home/ansi/inventories/group_vars/misc

Any way  to provide the pass to ARMS?

thanks

EDIT: Similiar to #104

**Comment by DerekTBrown** [comment]
@djordje-petrovic I am closing this in favor of #104.  Going to be taking a look at that in the next couple of days.
