### ISSUE TITLE
[Feature Request] Inline Playbook

### ISSUE THREAD

**Issue by DerekTBrown** [rundeck-plugins/ansible-plugin#127]
Fantastic plugin! I think it would be easier if there were an option to directly type a list of tasks inline (as opposed to having to link to a file).  Is this a possibility in the future?

**Comment by DerekTBrown** [comment]
Created PR:
https://github.com/Batix/rundeck-ansible-plugin/pull/128

**Comment by swtch1** [comment]
Since the PR was merged I think this issue can be closed, no?

**Comment by DerekTBrown** [comment]
Let me double check that the build was correct.

**Comment by DerekTBrown** [comment]
I seem to be seeing an error somewhere. The procArgs that are generated are the following:

```
 procArgs: [ansible-playbook-path, gather-hosts.yml, --inventory-file=/mnt/samba/CPU_Benchmark/inventory, -vvvv, --extra-vars=@/tmp/rundeck/ansible-runner2044685296147866412extra-vars, --user=user, --ask-pass, --become-method=sudo, --become-user=user]```
