### ISSUE TITLE
Now Live: Automatic Release Binaries

### ISSUE THREAD

**Issue by frozenice** [rundeck-plugins/ansible-plugin#132]
So, this is pretty neat: Instead of needing to manually build the .jar and upload it to GitHub and also build and push the Docker image to Docker Hub, we now only need to create a new release on GitHub and the rest will be taken care of by Travis CI! :)

The [contributing guide](https://github.com/Batix/rundeck-ansible-plugin/blob/master/CONTRIBUTING.md#releases) has been updated. There is no version in the Gradle file anymore, it is pulled from the release tag.

I'm leaving this issue open for a while to gather feedback or bugs.

**Comment by DerekTBrown** [comment]
Will Travis CI also report build status?

**Comment by DerekTBrown** [comment]
Also: is the version taken from the git tag, or the gradle build, or what is the deal?

**Comment by DerekTBrown** [comment]
Also: are we free to delete the Docker branch?

**Comment by frozenice** [comment]
> are we free to delete the Docker branch?

There were some E2E test related things, but I need to redo that anyway. I deleted the branch.

**Comment by DerekTBrown** [comment]
@frozenice can you set the master branch to protected? We should really all be making PRs to merge code.

**Comment by frozenice** [comment]
@DerekTBrown done, I also enabled "Restrict who can push to this branch", I hope you can still merge PRs with that setting.

**Comment by frozenice** [comment]
Btw @DerekTBrown please leave out the "v" in front of versions / tags, as this will get used for the .jar filename and the docker image tag.

**Comment by DerekTBrown** [comment]
@frozenice I cannot merge anymore, but we probably need some sort of review process anyway.

**Comment by frozenice** [comment]
@DerekTBrown okay, I disabled that setting again.
There is also "Require pull request reviews before merging":
> When enabled, all commits must be made to a non-protected branch and submitted via a pull request with at least one approved review and no changes requested before it can be merged into master.

We could enable that.

**Comment by DerekTBrown** [comment]
@frozenice can you disable "restrict who can push to this branch" but enable reviews?

**Comment by frozenice** [comment]
@DerekTBrown Done and done, didn't enable any sub-options of "reviews required".

**Comment by DerekTBrown** [comment]
@frozenice can we look at moving the repo to https://github.com/rundeck-plugins?

**Comment by frozenice** [comment]
@DerekTBrown What's the gain? It's already discoverable through http://rundeck.org/plugins/index.html and https://www.rundeck.com/ansible - I'd rather keep it here. Contributions can happen (and are happening) here, too.

**Comment by DerekTBrown** [comment]
Think we have gotten past bugs here, closing.
