### ISSUE TITLE
Playbook needs to be reset after upgrade to 2.1.3

### ISSUE THREAD

**Issue by jacobamey** [rundeck-plugins/ansible-plugin#137]
May be by design but all of my Rundeck Jobs in Rundeck after updating from 2.0.2 to 2.1.3 have the playbook field under workflow blanked out. This results in failure when running the playbook.

re-adding the playbook results in success. Only the playbook field seems to be blank so all other options are untouched.

May be a bug, may just be something you have to do. Either way, consider this an FYI to all ;-)

**Comment by DerekTBrown** [comment]
This is because the name of the field for the playbook field changed.  Good note.

**Comment by frozenice** [comment]
@DerekTBrown How about changing the field back?

**Comment by DerekTBrown** [comment]
https://github.com/Batix/rundeck-ansible-plugin/pull/140

**Comment by DerekTBrown** [comment]
This may cause some issues for people who are on 2.1.x.  I would suggest removing 2.1.x from releases and starting with 2.2.x

**Comment by frozenice** [comment]
I bet more people are using <2.1 than 2.1.x, so this shouldn't be a big issue.
Let's do it this way. I removed the releases and corresponding docker images.
@DerekTBrown you can do a 2.2.0 (sans "v" please), if the current master looks ok to you.
