### ISSUE TITLE
NodeStep for playbook and modules

### ISSUE THREAD

**Issue by ahonor** [rundeck-plugins/ansible-plugin#139]
The workflow step invokes ansible-playbook, delegating the node dispatching but at the loss of getting per-node log collation. It may be less efficient but at times more advantageous for some cases to use a NodeStep wrapper around ansible-playbook. As a nodestep, log capture plugins can look up output for a particular node, as well.

**Comment by DerekTBrown** [comment]
@ahonor this project used to have that functionality, but it was an extremely dirty solution and was removed.  If you are interested in implementing this functionality in a better way, we look forward to your PR.

**Comment by mcassaniti** [comment]
The code to run a workflow node step has been merged under #183. Closing.
