### ISSUE TITLE
Drop ansible-playbook and template module from AnsibleResourceModelSource

### ISSUE THREAD

**Issue by frozenice** [rundeck-plugins/ansible-plugin#14]
Investigate switching to `ansible all -m setup -t /tmp/...`.

**Comment by ktosiek** [comment]
Is running the setup necessary? If not, you could use a short python script that uses Ansible as library to load the inventory and dump it in a usable format. That will only give you the data available straight from the inventory, but you won't need to connect to nodes when loading the list of them.

**Comment by frozenice** [comment]
There already is an option to disable fact gathering on node discovery, see [the playbook](https://github.com/Batix/rundeck-ansible-plugin/blob/master/src/main/resources/gather-hosts.yml) I use for this. Enabling the fact_cache (as noted in #8) should return cached facts for the hosts when gathering is disabled.
Sounds like the playbook already does what your python script would do.

I thought about this some time ago and concluded I couldn't use the command in the OP, so closing this - feel free to comment nonetheless here or in #8.
