### ISSUE TITLE
Sporadic No Nodes Match

### ISSUE THREAD

**Issue by wesseljt** [rundeck-plugins/ansible-plugin#145]
I am sporadically getting "No Nodes Matched" on scheduled jobs when using ansible_module workflow step. Tailed service.log and ansible gathering facts is successful. I moved each project to a separate inventory file to see if that would help. I have also had a scheduled job fail and then immediately run it manually, which was successful.  

service.log file screenshots:
<img width="1394" alt="screen shot 2017-09-06 at 8 27 54 pm" src="https://user-images.githubusercontent.com/3269017/30140359-f3db1cba-9341-11e7-9550-d399e09f2c46.png">
<img width="1319" alt="screen shot 2017-09-06 at 8 28 04 pm" src="https://user-images.githubusercontent.com/3269017/30140358-f3d6b030-9341-11e7-88bf-b9ccf151f197.png">

Here is my project config:
#Wed Sep 06 20:25:17 EDT 2017
#edit below
ansible-ssh-auth-type=privateKey
ansible-ssh-keypath=/home/ubuntu/rsyncpw/ansible.pem
project.ansible-executable=/bin/bash
project.ansible-ssh-auth-type=privateKey
project.ansible-ssh-keypath=/home/ubuntu/rsyncpw/ansible.pem
project.description=
project.disable.executions=false
project.disable.schedule=false
project.jobs.gui.groupExpandLevel=1
project.name=Accounting
project.nodeCache.delay=300
project.nodeCache.enabled=true
resources.source.1.config.ansible-become=false
resources.source.1.config.ansible-gather-facts=true
resources.source.1.config.ansible-ignore-errors=true
resources.source.1.config.ansible-inventory=/etc/ansible/hosts_accounting
resources.source.1.type=com.batix.rundeck.plugins.AnsibleResourceModelSourceFactory
service.FileCopier.default.provider=com.batix.rundeck.plugins.AnsibleFileCopier
service.NodeExecutor.default.provider=com.batix.rundeck.plugins.AnsibleNodeExecutor

**Comment by DerekTBrown** [comment]
Can you execute the job in debug mode, and provide the log output?

**Comment by wesseljt** [comment]
Hey Derek. I "turned it off and on again" (restarted rundeck service) and haven't had any problems. I also increased memory on the VM. I haven't had any problems since.
