### ISSUE TITLE
Ansible Local Facts - Facts.d

### ISSUE THREAD

**Issue by bernardoVale** [rundeck-plugins/ansible-plugin#15]
I was wondering how this plugin could make use of [local facts](http://docs.ansible.com/ansible/playbooks_variables.html#local-facts-facts-d). I was reading issue #4 and discovered that facts are currently hardcoded. I've understood why it's difficult to implement something dynamic.

I'm using this feature a lot and it would be very nice to filter nodes by my local facts, I'm creating this issue to discuss how can we do this.

**Comment by frozenice** [comment]
According to the docs you linked, those facts are getting returned under `ansible_local.preferences.*`. Writing a mapping for each fact sounds like a burden and seeing that local facts can be complex JSON, it would need a smart automatic mapping and configuration - which would also solve #4 (continuing the discussion there).
