### ISSUE TITLE
Ansible Resource Model Source should support SSH Password Storage Path

### ISSUE THREAD

**Issue by jdlaroche** [rundeck-plugins/ansible-plugin#153]
All the ansible modules in the project configuration supports the SSH Password Storage Path. This allow you to use a private key stored in the key storage of Rundeck. Because this option isn't available for the Ansible Resource Model Source module, the key also have to copied manually on the Rundeck server.

I think it would really make sense to support the key storage in this module.

**Comment by DerekTBrown** [comment]
This is a feature we would love to have (https://github.com/Batix/rundeck-ansible-plugin/issues/96)! Feel free to submit a PR!

**Comment by FloThinksPi** [comment]
@DerekTBrown  can you please reopen this ? This is still an issue on the "Ansible Resource Model Source" as the only available fields are:
![image](https://user-images.githubusercontent.com/5863788/49238779-73d0ab80-f401-11e8-944f-06387b4b27ac.png)

however in a workflow step the needed fields are present:
![image](https://user-images.githubusercontent.com/5863788/49238870-ad091b80-f401-11e8-8bde-0f2721699b52.png)
