### ISSUE TITLE
Ansible integration with Rundeck on different hosts

### ISSUE THREAD

**Issue by mrondla** [rundeck-plugins/ansible-plugin#158]
Hi Guys

I am new to this, tried searching the issues, documents and other stuff related to Ansible and Rundeck integration, got some info, but that is not what i am looking for.

Can you please help me with the below questions that i have?

1. I have Ansible installed on one VM and Rundeck on another VM - Can we integrate both with this plugin?

Ansible host: 

OS = Linux
Ansible Version = 1.8.2

Rundeck host:
OS = Linux
Rundeck Version = 2.1.1

2. If yes, can you please help me with some procedure to start working on integration.

Thank you
Manoj

**Comment by rangsan** [comment]
Regarding to the document they need to be on the same machine.

**Comment by mrondla** [comment]
Thank you @rangsan, do we have any possibility to integrate them from different hosts?

**Comment by DerekTBrown** [comment]
@mrondla I don't see this as being a feature we would consider adding.  In order for Rundeck to access Ansible on a remote host, we would basically be re-inventing Ansible to do the connection brokering.  It is just a lot easier to have them all on one host.

**Comment by mrondla** [comment]
Thank you @DerekTBrown, appreciated your response. That make sense. I will try to find a solution for my case.
