### ISSUE TITLE
Lack of visibility in job execution results

### ISSUE THREAD

**Issue by menicolas89** [rundeck-plugins/ansible-plugin#159]
I ve setup a job and used the workflow tab to run a playbook on my nodes. The jobs works fine and so far all i am getting is a Success or Error indication for the execution. I seem to be missing some job execution related details in the interface (listed below), am I missing something or is this sth not available with ansible yet?

I am missing in the interface user-friendly  details such as the list of nodes and execution result, i would also expect to see the result for each tag (say for example see "web-production", "web-uat" etc. Instead of seeing hostnames. At the moment I can only see such details by going into the execution log results, but the information is mixed up with lots of info and barely accessible for our production support team for example. Lastly one feature I see missing is "re-execute" against failed target, a feature we ve had using bladelogic which was very helpful.

**Comment by menicolas89** [comment]
And just to be clearer, in my case the job node summary page is showing complete 0% 0/0 , failed incomplete etc. although my job ran on two nodes using ansible.
EDIT - Based on this page https://www.rundeck.com/ansible this is as expected and the feature I am looking for is not available yet : "Call Ansible playbooks and modules from Rundeck. Rundeck returns output as you would expect from ansible's command line". I am a little disappointed as this is a key feature missing, as nodes are being treated differently now that ansible is involved - I was expected a "view" that gave the impression each host had been accessed individually during the deployment. Right now the deployment status view is not making much sense while using ansible.

**Comment by DerekTBrown** [comment]
@menicolas89 this has been a topic of a lot of debate in this project (https://github.com/Batix/rundeck-ansible-plugin/issues/139).  The problem is that there is currently no way to manually set the status of a NodeStep from a WorkflowStep (this is a Rundeck, rather than a Rundeck Ansible Plugin issue).
