### ISSUE TITLE
Extra Arguments Can not be null?

### ISSUE THREAD

**Issue by zwxk14** [rundeck-plugins/ansible-plugin#16]
## env

rundeck 2.6.4
ansible-plugin-1.2.1.jar
### Case 1

when you created a step use "Ansible Module" or "Ansible Playbook" with rundeck-ansible-plugin, if the "Extra Arguments" field was not input anything,  you will got error like this:

> 2016-04-05 14:45:53,092 [Thread-52] ERROR com.dtolabs.rundeck.core.execution.workflow.steps.node.NodeStepPluginAdapter - Uncaught th
> rowable executing node step.
> java.lang.NullPointerException
>         at com.dtolabs.rundeck.core.utils.QuotedStringTokenizer.<init>(QuotedStringTokenizer.java:24)
>         at com.dtolabs.rundeck.core.utils.QuotedStringTokenizer.collectTokens(QuotedStringTokenizer.java:53)
>         at com.dtolabs.rundeck.core.utils.QuotedStringTokenizer.tokenizeToArray(QuotedStringTokenizer.java:39)
>         at com.dtolabs.rundeck.core.utils.OptsUtil.burst(OptsUtil.java:50)
>         at com.batix.rundeck.AnsibleRunner.extraArgs(AnsibleRunner.java:83)
>         at **com.batix.rundeck.AnsibleModuleNodeStep.executeNodeStep(AnsibleModuleNodeStep.java:28)**
>         at com.dtolabs.rundeck.core.execution.workflow.steps.node.NodeStepPluginAdapter.executeNodeStep(NodeStepPluginAdapter.java:1
> 06)
>         at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeNodeStep(ExecutionServiceImpl.java:149)
>         at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:116)
>         at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:58)
>         at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.dispatchToNodes(ExecutionServiceImpl.java:177)
>         at com.dtolabs.rundeck.core.execution.workflow.steps.NodeDispatchStepExecutor.executeWorkflowStep(NodeDispatchStepExecutor.java:66)
>         at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeStep(ExecutionServiceImpl.java:116)
>         at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWFItem(BaseWorkflowStrategy.java:225)
>         at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflowItemsForNodeSet(BaseWorkflowStrategy.java:303)
>         at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflowItemsForNodeSet(BaseWorkflowStrategy.java:258)
>         at com.dtolabs.rundeck.core.execution.workflow.StepFirstWorkflowStrategy.executeWorkflowImpl(StepFirstWorkflowStrategy.java:

if input a blank (or space) in the "Extra Arguments" field, the step will run without errors.
### Case2

if you not input anything in the "Extra Arguments field"  when you configure the project Default Node Executor, then run a "Commands" with Ansible Ad-Hoc Node Executor, you will got error like this:

> 2016-04-08 11:25:06,650 ERROR ExecutionUtilService - Execution failed: 573: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [172.17.20.79: Unknown: java.lang.NullPointerException]}, Node failures: {172.17.20.79=[Unknown: java.lang.NullPointerException]}, status: failed]

if input a blank (or space) in the "Extra Arguments" field, you will not see any errors.

**Comment by tanzhixu** [comment]
@zwxk14 I have the same error with you to Case 2, but when i input a blank in the 'Extra Arguments' field, i can run the job or command successful,

**Comment by frozenice** [comment]
Please try the [latest version](https://github.com/Batix/rundeck-ansible-plugin/releases)!
