### ISSUE TITLE
Upgrade Problem from 1.4.0 to 2.2.2

### ISSUE THREAD

**Issue by danitfk** [rundeck-plugins/ansible-plugin#160]
Hello ,

After I upgrade rundeck-ansible-plugin from 1.4.0 to 2.2.2 , I've got this error:
`

18:28:35 | localhost |   | com.dtolabs.rundeck.core.NodesmusicboxetEmptyException: No matched nodes: NodeSet{includes={name=NAME, dominant=false, }}
-- | -- | -- | --
18:28:35 |   |   | at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.validateNodeSet(NodeFirstWorkflowExecutor.java:350)
18:28:35 |   |   | at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.executeWorkflowImpl(NodeFirstWorkflowExecutor.java:88)
18:28:35 |   |   | at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflow(BaseWorkflowExecutor.java:317)
18:28:35 |   |   | at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:55)
18:28:35 |   |   | Exception: class com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{includes={name=NAME, dominant=false, }}
18:28:35 |   |   | No matched nodes: NodeSet{includes={name=NAME, dominant=false, }}
`

First I've downloaded .jar file and then replace with old plugin .jar .

Regards

**Comment by DerekTBrown** [comment]
Can you provide us with the configuration you are using?

**Comment by danitfk** [comment]
Hey Derek, 
You can find configuration here:
https://pastebin.mozilla.org/9073914

**Comment by danitfk** [comment]
Hey there, Is that helps you?

**Comment by mcassaniti** [comment]
Can't see your output on pastebin any longer. Are you still having an issue?
