### ISSUE TITLE
Take very long time fetching node facts

### ISSUE THREAD

**Issue by rangsan** [rundeck-plugins/ansible-plugin#164]
I have around 100 machines in my inventory both Windows and Linux. Every time I click the job, I can see rundeck execute simple ansible task to gather facts. The rundeck UI stuck waiting all nodes to be completed gathering facts. It's very slow especially Windows machines. 

Centos 6.9
Rundeck : 2.10.0.1
Ansible : 2.3.2.0

**Comment by bzlowrance** [comment]
I've noticed the same behavior, and have made the following changes to get around the problem.

project.nodeCache.delay=1209600
project.nodeCache.enabled=true

This will cache everything for 14 days, if you need to refresh sooner than this, you can manually kick off a node refresh job, or re-save the project.

**Comment by mcassaniti** [comment]
@rangsan Is this issue still relevant?

**Comment by mcassaniti** [comment]
Issue has gone stale. Closing. If you need further assistance then please post again.
