### ISSUE TITLE
Unknown: java.lang.NullPointerException

### ISSUE THREAD

**Issue by tanzhixu** [rundeck-plugins/ansible-plugin#17]
Failed dispatching to node 10.1.15.61: java.lang.NullPointerException
Failed dispatching to node 10.1.15.94: java.lang.NullPointerException
Failed dispatching to node 10.1.15.95: java.lang.NullPointerException
Execution failed: 41: [Workflow result: , step failures: {1=Dispatch failed on 3 nodes: [10.1.15.95: Unknown: java.lang.NullPointerException, 10.1.15.94: Unknown: java.lang.NullPointerException, 10.1.15.61: Unknown: java.lang.NullPointerException]}, Node failures: {10.1.15.95=[Unknown: java.lang.NullPointerException], 10.1.15.94=[Unknown: java.lang.NullPointerException], 10.1.15.61=[Unknown: java.lang.NullPointerException]}, status: failed]

**Comment by frozenice** [comment]
Seems like a dupe of #16.
