### ISSUE TITLE
Error in while running ansible playbook using plugin.

### ISSUE THREAD

**Issue by rsathish4433** [rundeck-plugins/ansible-plugin#172]
HI  ,
 I have installed ansible plugin and created a job for ping.yml as shown in the vidoe (https://www.rundeck.com/ansible).  while running getting below error

/tmp/rundeck/ansible-rundeck1189222681543563995
Execution failed: 41 in project Automation_project: [Workflow result: , step failures: {1=AnsibleError: /tmp/rundeck/ansible-rundeck1189222681543563995}, status: failed]

Thanks
Sathish Rangan

**Comment by mcassaniti** [comment]
Can you please include your Playbook? I did look at the Playbook from the video and it seems simple enough. Also, do your nodes have enough information to support logging onto such as hostname, username and password?

**Comment by mcassaniti** [comment]
Issue has gone stale. Closing. If you still need assistance, please feel free to post and I'll re-open.
