### ISSUE TITLE
Version bump (and release documentation)

### ISSUE THREAD

**Issue by mcassaniti** [rundeck-plugins/ansible-plugin#173]
Can the version be bumped, or can I get consensus from @DerekTBrown or @frozenice to bump the version? Is there any documented method to determine when a new release will be produced?

**Comment by frozenice** [comment]
see [here](https://github.com/Batix/rundeck-ansible-plugin/blob/master/CONTRIBUTING.md#releases) :)
Basically: determine a new version and create a tag, that's all.

**Comment by mcassaniti** [comment]
@frozenice Missed that this was closed. I'm going to do a new release unless there's objections.
