### ISSUE TITLE
Rundeck Ansible Plugin doesn't pass any password in job

### ISSUE THREAD

**Issue by nsn-amagruder** [rundeck-plugins/ansible-plugin#179]
I configured Rundeck Ansible Playbook to run.  It would not pass sudo user password into the job so I configured CentOS to remove sudo requirements. Then job was passing rundeck as the ssh user so I added the ssh credentials to the job.  Now it won't pass the SSH password.  I have ansible play configured with all the password and would rather run just the ansible-playbook without having rundeck pass any credentials.

Is there a way to get rundeck to enter in configured sudo and ssh password or not need to?

Warning: Password input may be echoed.
--
14:46:55 |   |   | SUDO password
Doesn't enter SUDO password

Warning: Password input may be echoed.
--
20:12:59 |   |   | SSH password:
Does enter SSH Password

**Comment by mcassaniti** [comment]
You can run with the job in debug mode and look at the command line for Ansible, along with the contents of any files that are generated? This should at least assist to track down the problem.
