### ISSUE TITLE
Using /etc/ansible/ansible.cfg as config fileERROR! Specified --limit does not match any hosts

### ISSUE THREAD

**Issue by d053** [rundeck-plugins/ansible-plugin#18]
on my first installations of the plugin

i get the follogwing errro if i try to run a job, either with the module or playbook "module"
can someone point me to something? i am clueless.

thanks alot!

```
13:56:50                  [workflow] Begin step: 1,NodeDispatch
13:56:50            1: Workflow step executing: StepExecutionItem{type='NodeDispatch', keepgoingOnSuccess=false, hasFailureHandler=false}
13:56:50            preparing for sequential execution on 1 nodes
13:56:50            Executing command on node: doit, NodeEntryImpl{tags=[], attributes={nodename=doit, hostname=doit.rocketbase.de, osVersion=3.13.0-32-generic, osFamily=unix, osArch=amd64, description=Rundeck server node, osName=Linux, username=ste}, project='null'}
13:56:50            [workflow] beginExecuteNodeStep(doit): NodeDispatch: StepExecutionItem{type='NodeDispatch', keepgoingOnSuccess=false, hasFailureHandler=false}
13:56:50            Using /etc/ansible/ansible.cfg as config fileERROR! Specified --limit does not match any hosts
13:56:50            [workflow] finishExecuteNodeStep(doit): NodeDispatch: AnsibleNonZero: Ansible exited with non-zero code.
13:56:50            1: Workflow step finished, result: Dispatch failed on 1 nodes: [doit: AnsibleNonZero: Ansible exited with non-zero code.]
13:56:50            [workflow] Finish step: 1,NodeDispatch
13:56:50            [workflow] Finish execution:  rundeck-workflow-node-first: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [doit: AnsibleNonZero: Ansible exited with non-zero code.]}, Node failures: {doit=[AnsibleNonZero: Ansible exited with non-zero code.]}, status: failed]
13:56:50            [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [doit: AnsibleNonZero: Ansible exited with non-zero code.]}, Node failures: {doit=[AnsibleNonZero: Ansible exited with non-zero code.]}, status: failed]
13:56:50            Execution failed: 134: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [doit: AnsibleNonZero: Ansible exited with non-zero code.]}, Node failures: {doit=[AnsibleNonZero: Ansible exited with non-zero code.]}, status: failed]
```

**Comment by frozenice** [comment]
Seems like Ansible doesn't know the node `doit`. Did you select "Dispatch to Nodes" or "Execute locally" in your job config under "Nodes"? Do you have a host named "doit" in your Ansible inventory?

**Comment by d053** [comment]
I tried both, "Dispatch to Node" and "Execute locally"

part from debug log:

<snip>
xecuting command on node: doit, NodeEntryImpl{tags=[],
attributes={nodename=doit, hostname=doit.w00t.com,
osVersion=3.13.0-85-generic, osFamily=unix, osArch=amd64,
description=Rundeck server node, osName=Linux, username=ste},
project='null'}
17:12:22 [workflow] beginExecuteNodeStep(doit): NodeDispatch:
StepExecutionItem{type='NodeDispatch', keepgoingOnSuccess=false,
hasFailureHandler=false}
17:12:22 Failed executing node plugin
[com.batix.rundeck.AnsiblePlaybookNodeStep] on node doit:
java.lang.NullPointerException at
com.dtolabs.rundeck.core.utils.QuotedStringTokenizer.<init>(QuotedStringTokenizer.java:24)
at
com.dtolabs.rundeck.core.utils.QuotedStringTokenizer.collectTokens(QuotedStringTokenizer.java:53)
at
com.dtolabs.rundeck.core.utils.QuotedStringTokenizer.tokenizeToArray(QuotedStringTokenizer.java:39)
at com.dtolabs.rundeck.core.utils.OptsUtil.burst(OptsUtil.java:50) at
com.batix.rundeck.AnsibleRunner.extraArgs(AnsibleRunner.java:83) at
com.batix.rundeck.AnsiblePlaybookNodeStep.executeNodeStep(AnsiblePlaybookNodeStep.java:27)
at
com.dtolabs.rundeck.core.execution.workflow.steps.node.NodeStepPluginAdapter.executeNodeStep(NodeStepPluginAdapter.java:106)
at
com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeNodeStep(ExecutionServiceImpl.java:149)
at
com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:116)
at
com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:58)
at
com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.dispatchToNodes(ExecutionServiceImpl.java:177)
at
com.dtolabs.rundeck.core.execution.workflow.steps.NodeDispatchStepExecutor.executeWorkflowStep(NodeDispatchStepExecutor.java:66)
at
com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeStep(ExecutionServiceImpl.java:116)
at
com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWFItem(BaseWorkflowStrategy.java:225)
at
com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflowItemsForNodeSet(BaseWorkflowStrategy.java:303)
at
com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflowItemsForNodeSet(BaseWorkflowStrategy.java:258)
at
com.dtolabs.rundeck.core.execution.workflow.StepFirstWorkflowStrategy.executeWorkflowImpl(StepFirstWorkflowStrategy.java:79)
at
com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflow(BaseWorkflowStrategy.java:182)
at
com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowStrategy$DispatchedWorkflow.dispatch(NodeFirstWorkflowStrategy.java:383)
at
com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:118)
at
com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:64)
at
com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.dispatchToNodes(ExecutionServiceImpl.java:196)
at
com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowStrategy.executeWFSectionNodeDispatch(NodeFirstWorkflowStrategy.java:189)
at
com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowStrategy.executeWorkflowImpl(NodeFirstWorkflowStrategy.java:110)
at
com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflow(BaseWorkflowStrategy.java:182)
at
com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:55)
</snip>

2016-04-14 21:22 GMT+02:00 David Kirstein notifications@github.com:

**Comment by frozenice** [comment]
> Do you have a host named "doit" in your Ansible inventory?

You didn't answer this.

**Comment by d053** [comment]
ups, sorry.. yes.. i have.

2016-04-25 19:09 GMT+02:00 David Kirstein notifications@github.com:

**Comment by frozenice** [comment]
Can you give the new [v1.2.3](https://github.com/Batix/rundeck-ansible-plugin/releases/tag/1.2.3) a shot?

**Comment by vuliad** [comment]
Same error. 
Is it possible to execute ansible without given --limit option? I want it optionaly, because hosts already specified in my playbook. 
Simple workaround is to add "--limit all" as extra argument in job settings
http://dl.dropbox.com/u/937100/screenshots/screen160507-221933.png

**Comment by frozenice** [comment]
Can you please try the new [v1.2.4](https://github.com/Batix/rundeck-ansible-plugin/releases/tag/1.2.4)? See the [README](https://github.com/Batix/rundeck-ansible-plugin#debugging) on how to enable debugging!

**Comment by lunawesley9** [comment]
i have 1.2.4 same issue . seems related to #28

**Comment by frozenice** [comment]
There were newer versions released in the meantime, so test the newest version please.

Closing this one, similar thing as #32.
