### ISSUE TITLE
Not able to copy a file from ansible node to destination node

### ISSUE THREAD

**Issue by aswath110** [rundeck-plugins/ansible-plugin#19]
Hi i am running ansible playbook from rundeck.. In my ansible playbook there is command to copy a file from anisble node to dest node.. In play book i gave like this 
- name: copy file to the server
  copy: src=/root/{{ filename }}/ dest=/opt/
  register: status 
  
  This thing works when i run ansible in command prompt.. But when i run through Rundeck it is showing error like it is not able to find the file.. During project creation i selected (Ansible File Copier) and gave arguments in a job in a correct format.. Output which i get in rundeck logs is

---

 [copy file to the server] *********************************************\* 
failed: [172.30.10.234] => {"failed": true}
msg: could not find src=/root/test
## FATAL: all hosts have already failed -- aborting

Please help me what i am doing wrong

**Comment by frozenice** [comment]
You are doing nothing wrong. :) This is an open feature request, see #10.
