### ISSUE TITLE
ERROR! Specified hosts and/or --limit does not match any hosts

### ISSUE THREAD

**Issue by blinkesto** [rundeck-plugins/ansible-plugin#195]
I got this error "ERROR! Specified hosts and/or --limit does not match any hosts" after updating my ansible inventory file but after a while it went away so I guess it just took some time to update?  Is there a way to force that update?

**Comment by mcassaniti** [comment]
If you're importing your list of nodes in from Ansible to Rundeck, the resource model has a cache that can be configured. I'd dare say the cache did not yet have your selected node initially, but did when running it later. There is however no option to refresh the cache upon a change to the inventory file on the Ansible side. Your best option is to build a job which refreshes the project nodes as a workflow step. You would run this job manually when the Ansible inventory changes.
