### ISSUE TITLE
Unable to find role

### ISSUE THREAD

**Issue by rahulsinghai** [rundeck-plugins/ansible-plugin#196]
Ansible version: 2.4.1.0
Rundeck version: 3.0.2
Rundeck's ansible-plugin version: 2.5.0
Linux version: RHEL 6.9 (Santiago) x86_64
Python version: 2.6.6

I am using roles to structure my playbooks:

    /work/ansible/
    ├── roles
    │   └── test-playbook
    │       └── tasks
    │           └── main.yml
    └── test-playbook.yml

/work/ansible/test-playbook.yml

    ---
    - hosts: [localhost]
      roles:
        - test-playbook

/work/ansible/roles/test-playbook/tasks/main.yml

    ---
    - ping:

When I execute playbook directly, it works as expected:

    $ ansible-playbook /work/ansible/test-playbook.yml
     [WARNING]: Could not match supplied host pattern, ignoring: all
    
     [WARNING]: provided hosts list is empty, only localhost is available
    
    
    PLAY [localhost] *****************************************************************************************************
    
    TASK [Gathering Facts] ***********************************************************************************************
    Friday 24 August 2018  23:37:48 +0100 (0:00:00.129)       0:00:00.129 *********
    ok: [localhost]
    
    TASK [test-playbook : ping] ******************************************************************************************
    Friday 24 August 2018  23:37:49 +0100 (0:00:00.859)       0:00:00.988 *********
    ok: [localhost]
    
    PLAY RECAP ***********************************************************************************************************
    localhost                  : ok=2    changed=0    unreachable=0    failed=0
    
    Friday 24 August 2018  23:37:49 +0100 (0:00:00.247)       0:00:01.236 *********
    ===============================================================================
    Gathering Facts ----------------------------------------------------------------------------------------------- 0.86s
    test-playbook : ping ------------------------------------------------------------------------------------------ 0.25s

But, when I run it using Rundeck (even via Ansible playbook workflow step via GUI), I get following error:

    $ sudo su - rundeck -s /bin/bash -c "ansible-playbook /work/ansible/test-playbook.yml"
     [WARNING]: Could not match supplied host pattern, ignoring: all
    
     [WARNING]: provided hosts list is empty, only localhost is available
    
    ERROR! the role 'test-playbook' was not found in /work/ansible/roles:/var/lib/rundeck/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/work/ansible
    
    The error appears to have been in '/work/ansible/test-playbook.yml': line 5, column 7, but may
    be elsewhere in the file depending on the exact syntax problem.
    
    The offending line appears to be:
    
      roles:
        - test-playbook
          ^ here

**Comment by mcassaniti** [comment]
Does the rundeck user have sufficient permission to access your roles? My first thought was that Ansible didn't properly know the path to your roles (hence the Ansible base path option on the workflow step), but I can see from the output that it is searching in the right place for the role.

**Comment by rahulsinghai** [comment]
Thanks @mcassaniti 
**_rundeck_** user needs execute permission on _roles_ folder.

In my case, the _roles_ folder had **_drwxr--r-x_** permissions.
Since _rundeck_ user belonged to the same group as the owner of _roles_ folder, it didn't had execute permission.
After giving execute permission to group (**_drwxr-xr-x_**), I was able to run the role.
