### ISSUE TITLE
Failed: AnsibleNonZero: Ansible exited with non-zero code.

### ISSUE THREAD

**Issue by elbanditos** [rundeck-plugins/ansible-plugin#20]
we use 1.2.2 plugin in rundeck on a fresh install with user admin.
A run command or job fail with error "Failed: AnsibleNonZero: Ansible exited with non-zero code."

[ansible_pluggin.txt](https://github.com/Batix/rundeck-ansible-plugin/files/221315/ansible_pluggin.txt)

**Comment by frozenice** [comment]
Can you tell me how your step was configured? Does it work if you use Ansible manually?

**Comment by elbanditos** [comment]
Hi,
Yes ansible run correctly alone with
Ansible all -m ping
Or with rundeck user
Su  rundeck -s .... -c ansible ... As in  the  web document
Platform rhel install with rpm jar module in ../libext no extra parameter
Usage with user admin (from install) 
Rundeck's acl are ok
Problem appends on job or for runnings commands.
So node executor with ansible is on , and other things too
Stephane

vendredi, 15 avril 2016, 07:23PM +0200 de David Kirstein < notifications@github.com >:

**Comment by elbanditos** [comment]
problem solved. 
ansible log was empty on action with rundeck.. 
/var/log/ansible was'nt accessible with user rundeck.
Thank and sorry for the disagreement.
However only the last pluggin (1.2.2) works for us.

**Comment by ghost** [comment]
I have the same issue with plugin version 1.3 and I have full access to ansible.log file
