### ISSUE TITLE
The plugins is trying to create the data directory in / (root) instead of /tmp/rundeck/ansible-hosts.*.

### ISSUE THREAD

**Issue by ecsumed** [rundeck-plugins/ansible-plugin#21]
Don't know why but the plugin is creating a data directory in "/" (root) instead of /tmp/rundeck/"ansible-hosts/"

This is the ansible log when it was trying to create a "data" directory in "/". 
`2016-04-26 06:27:34,810 p=1556 u=rundeck |  invalid output was: Traceback (most recent call last):
  File "/var/lib/rundeck/.ansible/tmp/ansible-tmp-1461652054.64-12936011354221/file", line 1675, in <module>
    main()
  File "/var/lib/rundeck/.ansible/tmp/ansible-tmp-1461652054.64-12936011354221/file", line 216, in main
    os.mkdir(curpath)
OSError: [Errno 13] Permission denied: '/data'`

This is the ansible log after I created the '/data' directory in root (just to see if it works). 
`2016-04-26 06:46:05,945 p=1642 u=rundeck |  TASK: [template src=host-tpl.j2 dest="data/{{inventory_hostname}}"] *********** 
2016-04-26 06:46:06,172 p=1642 u=rundeck |  failed: [my_ip -> 127.0.0.1] => {"failed": true}
2016-04-26 06:46:06,173 p=1642 u=rundeck |  msg: Destination directory data does not exist`

Obviously, "/tmp/rundeck/ansible-hosts/data" doesn't exist because data was created in "/" (root).

`su rundeck -s /bin/bash -c "ansible all -m ping"` works without any issues.

Is there something that I'm missing? 

This is all on a fresh installation of Debian 8 on a VM via vagrant.
ansible 1.7.2
ansible-plugin-1.2.2

**Comment by javierurien** [comment]
Similar problem here.
But the data directory it looks for is /tmp/rundeck/ansible-hosts<id>/data. This directory does not exist.

ansible 2.0.2.0
ansible-plugin-1.2.2

I created a bash script that detects and creates /tmp/rundeck/ansible-hosts<id>/data and have since not had an exception as described on parent.

Now I find that I may not know how to use rundeck, because nothing changed, except that I do not get the "Error reading data." Message =P

Regards

**Comment by javierurien** [comment]
Invoking:
su rundeck -s /bin/bash -c "ansible-playbook /tmp/rundeck/ansible-hosts6856473879874453697/gather-hosts.yml -vvvv

I get:
TASK [template] ****************************************************************
task path: /tmp/rundeck/ansible-hosts6856473879874453697/gather-hosts.yml:9
ESTABLISH LOCAL CONNECTION FOR USER: rundeck
localhost EXEC /bin/sh -c '( umask 22 && mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1461701727.56-24285521689116`" && echo "`echo $HOME/.ansible/tmp/ansible-tmp-1461701727.56-24285521689116`" )'
localhost PUT /tmp/tmpFiYC3b TO /var/lib/rundeck/.ansible/tmp/ansible-tmp-1461701727.56-24285521689116/stat
localhost EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /var/lib/rundeck/.ansible/tmp/ansible-tmp-1461701727.56-24285521689116/stat'
localhost PUT /tmp/tmp8npzzx TO /var/lib/rundeck/.ansible/tmp/ansible-tmp-1461701727.56-24285521689116/source
localhost PUT /tmp/tmpcdVfx7 TO /var/lib/rundeck/.ansible/tmp/ansible-tmp-1461701727.56-24285521689116/copy
localhost EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /var/lib/rundeck/.ansible/tmp/ansible-tmp-1461701727.56-24285521689116/copy'
localhost EXEC /bin/sh -c 'rm -f -r /var/lib/rundeck/.ansible/tmp/ansible-tmp-1461701727.56-24285521689116/ > /dev/null 2>&1'
fatal: [codos -> localhost]: FAILED! => {"changed": true, "failed": true, "invocation": {"module_args": {"backup": false, "content": null, "delimiter": null, "dest": "data/codos", "directory_mode": null, "follow": true, "force": true, "group": null, "mode": null, "original_basename": "host-tpl.j2", "owner": null, "regexp": null, "remote_src": null, "selevel": null, "serole": null, "setype": null, "seuser": null, "src": "/var/lib/rundeck/.ansible/tmp/ansible-tmp-1461701727.56-24285521689116/source", "validate": null}}, "msg": "Destination data not writable"}

So apparently there's another directory with permissions problems.

Will keep looking.

Regards

**Comment by ecsumed** [comment]
@javierurien Yep, permission issues. Have you gotten it working yet? Thanks.

Cheers

**Comment by javierurien** [comment]
@ecsumed No, gave up waiting for some feedback here ;)... I am a noob with ansible and rundeck, so I was hoping someone more knowledgeable would help us!
If I get some improvement I will came back here...

regards

**Comment by ecsumed** [comment]
@javierurien Yeah, I guess we'll have to wait and see.

Cheers

**Comment by suivethefirst** [comment]
This seems to be related to #22 in which the same problem is occurring and seems to be preventing loading Ansible hosts.

**Comment by frozenice** [comment]
Can you give the new [v1.2.3](https://github.com/Batix/rundeck-ansible-plugin/releases/tag/1.2.3) a shot?

**Comment by ecsumed** [comment]
@frozenice Yep, tested it and its works now. Thanks.

@javierurien FYI.

**Comment by javierurien** [comment]
Sorry for the late feedback... I still have the same problem. I didn't have much time to explore. I hope I will now. Will be back with more info (hopefully)

Regards
