### ISSUE TITLE
Load ansible hosts on Rundeck startup

### ISSUE THREAD

**Issue by tdhulster** [rundeck-plugins/ansible-plugin#210]
Hi,

We have a Rundeck setup that uses the rundeck-ansible-plugin. 

But when the Rundeck container reboots, we first have to manually go to a project and click on 'Nodes' before it starts loading the Nodes/hosts.

Is it possible to load all nodes from the projects as soon the container is started?

**Comment by ltamaster** [comment]
Hi @tdhulster ,

Probably that is not controled by the plugin itself, maybe you can try with `First Load Asynch: true/false`
https://rundeck.org/docs/administration/configuration/configuration-file-reference.html#node-cache

Luis

**Comment by tdhulster** [comment]
@ltamaster thanks for the tip but unfortunately we get the same result.

We still have to click on the project and the job before it starts effectively loading its nodes :(
