### ISSUE TITLE
adhoc if you do not set Gather Facts: Yes

### ISSUE THREAD

**Issue by cdstg** [rundeck-plugins/ansible-plugin#213]
Hi had a project with playbooks and jobs like module they are all working 
and there is a an Ansible Resource Model Source with Gather Facts: NO

if you then run an adhoc command on a node you get  Unknown: java.lang.NullPointerException, 
I finnaly found you need to enable the Gather Facts: Yes to get rid of that error 

I m not sure why or if this is a bug

**Comment by ghost** [comment]
I am also experiencing this issue on 3.1.2 and can confirm that changing Gather Facts back to "Yes" fixes it. How can adhoc commands be allowed when Gather Facts is set to "No"?
