### ISSUE TITLE
rebuild docker image so ansible will get updated

### ISSUE THREAD

**Issue by mbigras** [rundeck-plugins/ansible-plugin#233]
Hi Batix Team,

Thank you for much building this image!
It's been working great.

I'm using the [`batix/rundeck-ansible:2.5.0`](https://hub.docker.com/r/batix/rundeck-ansible/tags) image which has `ansible 2.5.5` installed. I'd like to keep using your image but need features in ansible 2.7.

I cloned the repo, downloaded the jar file, and rebuilt the image and found that the image built with `ansible 2.7.0`. I didn't need to make any code changes, because the [Dockerfile uses latest alpine](https://github.com/Batix/rundeck-ansible-plugin/blob/d1233c4b301f46d3b71070fbecc43b4ac64fc642/Dockerfile#L1) which has a newer ansible.

Can you build a new image and push it to DockerHub?

**Comment by frozenice** [comment]
Hello @mbigras! I am glad it works for you.

I triggered a new release and [batix/rundeck-ansible:2.5.1](https://hub.docker.com/r/batix/rundeck-ansible/tags) is now available on Docker Hub. [Logs](https://travis-ci.com/Batix/rundeck-ansible-plugin/builds/103482175#L647) show that Ansible 2.7.0 got installed.

Please try it out and let me know if it's good! :)

**Comment by mbigras** [comment]
Thank you so much @frozenice you rock!
