### ISSUE TITLE
Rundeck does not process groups correctly

### ISSUE THREAD

**Issue by kurzroman** [rundeck-plugins/ansible-plugin#244]
I have an inventory:
```json
{
  "_meta": {
    "hostvars": {
      "fox": {
        "ansible_host": "10.10.10.2"
      }
    }
  },
  "all": {
    "children": [
       "reverse_proxy"
    ]
  },
  "reverse_proxy": {
    "hosts": [
      "fox"
    ]
  }
}
```

This inventory gets imported into rundeck and shows like this:
![image](https://user-images.githubusercontent.com/6129115/59202645-33ff3380-8b9d-11e9-94ec-f5cc3a57eb1e.png)
(Gather facts is disabled, but problem occurs with and without gather facts)

Then I have a playbook like this:
```yaml
---
- hosts: reverse_proxy
  gather_facts: no
  tasks:
    - name: Debug message
      debug:
        msg: "Hello world!"
```
Note that the hosts for that playbook are limited to the group reverse_proxy

If I execute the playbook via rundeck with "Generate inventory" setting enabled I get this error:
```
PLAYBOOK: reverse-proxy.yml ****************************************************
16:27:01			1 plays in reverse-proxy.yml
16:27:01			 [WARNING]: Could not match supplied host pattern, ignoring: reverse_proxy
16:27:01			
16:27:01			PLAY [reverse_proxy] ***********************************************************
16:27:01			skipping: no hosts matched
16:27:01			
16:27:01			PLAY RECAP *********************************************************************
```

The problem is that the generated inventory from rundeck does not add the original groups to the temporary inventory for the job. This is the inventory passed to the ansible command by rundeck:
```
{
  "all": {
    "hosts": {
      "fox": {
        "nodename": "fox",
        "hostname": "10.10.10.2",
        "ansible_host": "10.10.10.2",
        "username": "rundeck",
        "tags": "reverse_proxy"
      }
    },
    "children": {}
  }
}
```

This makes the hosts property for playbooks completely useless and is not compliant with how ansible playbooks should work.
Also it destroys the ability to create a job which selects hosts from different groups but takes different actions on the different groups.

OS: Ubuntu 18.04
Ansible Version: 2.8.1
Rundeck Version: 3.0.22
Plugin: 3.0.1

Also before creating this issue I looked through the other issues and it might be that issue #147 and #184 are caused by the problem described above.

**Comment by a118n** [comment]
Can confirm. I've got a multi-play multi-groups play which is basically useless because Rundeck ignores hosts properties in a playbook and wants to do it by itself. I didn't find the option to delegate host management to ansible playbook.

**Comment by marzdgzmn** [comment]
I'm experiencing the same issue. How did you resolve this?

**Comment by ggwena** [comment]
PR #278 does the trick!
