### ISSUE TITLE
Execute ansible playbook without --limit option if it set to execute localy

### ISSUE THREAD

**Issue by vuliad** [rundeck-plugins/ansible-plugin#25]
Hi. There are 2 options: execute localy and execute on nodes. 
Is it realy necessary to set --limit option to ansible if we have job setting = execute localy?

I already has tons of playbooks - and it already has hosts in it:

```
- name: TEST
  hosts: test
  roles:
    - test
```

Simple workaround for now is to add "--limit all" as extra argument in job settings
http://dl.dropbox.com/u/937100/screenshots/screen160507-221933.png

**Comment by frozenice** [comment]
This configuration seems to run the playbook for each selected node. Can't you set the strategy to "Step-oriented", so the playbook is only run once for this step?

I think "Execute locally" is the same as dispatching it to the server node. Needs some checks and suggestions.

**Comment by frozenice** [comment]
Closing this one, similar thing as #32.
