### ISSUE TITLE
--limit [rundeck-server] and not honoring "Disable Limit" flag

### ISSUE THREAD

**Issue by anlx-sw** [rundeck-plugins/ansible-plugin#251]
Hi, 
I've got a problem with the workflow node step executor on rundeck 3.1.0-20190731.
I specify the job to "Execute locally" and have set the "Disable Limit" option in the defintion of my Ansible Ressource Model Source. 

When i run the job the "procArgs:" show me the following line:
procArgs: [ansible-playbook, playbook/ansible-host/sync-netbox.yml, -l, hostname-rundeckserver, -vvv]

Similar problem to #176

So rundeck is limiting the "execute locally" job to my hostname-rundeckserver instead of passing it of without the limit parameter. The job then matches not the hosts: localhost definition in the playbook and fails to run therefore.

If i run the playbook with ansible-playbook command directly and the same inventory source it works without any problem using hosts: localhost.

what might be noteworthy in my installation is, that i use a inventory plugin which populates my inventory. the rundeck server is shown as hostname-rundeckserver in my rundeck nodes view.

What can i change, that the "Disable limit" flag is honored?

**Comment by anlx-sw** [comment]
I found the issue. The "Disable Limit" Flag is only working for the "Ansible Playbook" but not for the "Ansible Playbook Workflow Node Step". The "Ansible Playbook" option was only visible in the workflow steps view of the step. thats why i first didn't see that there are additional options.

**Comment by FloBEAUG** [comment]
Hello,

I have the same issue with playbook jobs returning "--limit does not match any hosts" 
I don't find the flag your mentioning. Can you explain how do you set it please ?

I didn't have the problem before v3.1.0 (now I'm in 3.1.2)
