### ISSUE TITLE
ssh-agent support

### ISSUE THREAD

**Issue by sgalam** [rundeck-plugins/ansible-plugin#252]
Is it possible use ssh-agent within this plugin?

What is the best practice to do this with rundeck-ansible-plugin? I cannot find a solution right now.
Thanks

**Comment by sgalam** [comment]
found another issue that ask the same with https://github.com/Batix/rundeck-ansible-plugin/issues/242

**Comment by linuxmail** [comment]
hi,

Rundeck would implement that feature for USD 20,000. My company would pay around  USD 5,000. So if we find others for the rest, we can get it into Rundeck.

**Comment by ahonor** [comment]
@linuxmail This is a useful enhancement and Rundeck wants to provide community support for the change. There is a pending [PR](https://github.com/Batix/rundeck-ansible-plugin/pull/257) for it now.

**Comment by frozenice** [comment]
The PR was just merged and a [new version](https://github.com/Batix/rundeck-ansible-plugin/releases/tag/3.1.0) was released. Please try it out! :)

**Comment by linuxmail** [comment]
hi @ahonor 

I'm speechless  :1st_place_medal:  

thanks so much !
