### ISSUE TITLE
cleanup ansible-runner files?

### ISSUE THREAD

**Issue by mtcoffee** [rundeck-plugins/ansible-plugin#258]
Maybe this is just cofiguration, but /tmp/rundeck is leaving ansible-runner files behind. This is an issue when senstive information is in the playbook/variables files. Is there a setting to autopurge these files after execution?

**Comment by jimr6007** [comment]
Just wanted to clarify that in my case it's not "/tmp/rundeck" but it's /tmp.
I could do a Rundeck or cron job to clean up the dir every hour or so but well, that seems not good.

I am definitely not a programmer but I can understand code for the most part if it's not super complicated :) 

I'm almost sure that when we get to this point "tempFile" is still null, so of course nothing happens.

        if (tempFile != null && !tempFile.delete()) {
          tempFile.deleteOnExit();
        }      

I'm dying to know though, at what point in the code, AnsibleRunner.java, what line or lines say "write the the temp playbook and extra vars files to /tmp"

it kinda seems like "write to /tmp" is a fallback/default option.

Just for my own sanity or teaching a novice a little bit, could you point me to the part of the code that triggers writing these files to /tmp.

Thanks !!

**Comment by jimr6007** [comment]
I cloned https://github.com/mcassaniti/rundeck-ansible-plugin/tree/tmp_vars_file_cleanup, built it and installed it and tested, still seeing the same behavior.

**Comment by frozenice** [comment]
Both PRs are merged and released as [3.1.1](https://github.com/Batix/rundeck-ansible-plugin/releases/tag/3.1.1).
