### ISSUE TITLE
SSH Keys - Configuration clarifications

### ISSUE THREAD

**Issue by SecT0uch** [rundeck-plugins/ansible-plugin#263]
I have difficulties making Rundeck use my Ansible SSH keys. Here is my configuration:
* Ubuntu Server 18.04.3 LTS (Up-to-date)
* Ansible 2.9.4 [Installed using the official Ansible PPA](https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#installing-ansible-on-ubuntu).
* Open Source Rundeck 3.2.1.20200113 [Installed using the official Rundeck repo](https://docs.rundeck.com/docs/administration/install/linux-deb.html#open-source-rundeck).

I configured Ansible for a **non-root user**, using a **Ed25519 SSH key**.

Despite :
> No SSH-Keys need to be shared between Ansible and Rundeck

I get a key related error when running `su rundeck -s /bin/bash -c "ansible all -m ping"`:
```bash
X.X.X.X | UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh: Host key verification failed.", 
    "unreachable": true
}
```
I can't figure out how to make rundeck use that key.
I tried copying `id_ed25519`, chown it to rundeck:rundeck and specifying the full path under the **SSH Key File path** option with no luck.

What would be the right way to make it work given my configuration ?

**Comment by mcassaniti** [comment]
I'll try to write this out for anyone seeing this issue in the future too.

With SSH you can have the user authenticate using SSH public key based authentication. I'm going to call this the user key. With SSH you will **always** have the host authenticate to the user using its own SSH key or keys. I'm going to call this the host key.

In your case the host key sent by the server was not known to Ansible, or more importantly the `rundeck` user. This caused host key verification to fail.

My suggestion to fix this is to run the following **once**, and run it again for any new machines.
`su rundeck -s /bin/bash -c "ANSIBLE_HOST_KEY_CHECKING=false ansible all -m ping"`

If a host is rebuilt then it's SSH host key will change and cause verification to fail again. A bit of an Internet search will help with this one.

**Comment by SecT0uch** [comment]
I had something missing in my Ansible configuration : 
By default rundeck try to login to the remote hosts with the (non-exitent) `rundeck` user. 
I had to edit `/etc/ansible/hosts` to add the variable `ansible_user`.

I still had to copy my original SSH key to  `/var/lib/rundeck/.ssh/` and execute `chown rundeck:rundeck /var/lib/rundeck/.ssh/*`
