### ISSUE TITLE
force Rundeck node cache reload/refresh

### ISSUE THREAD

**Issue by jimr6007** [rundeck-plugins/ansible-plugin#270]
it seems sensible to set the Rundeck node cache to something like an hour, of course you can set it to 60 seconds, but for this question let's just say it's set to one hour. If I do set it to 60 seconds, this plugin will ping every node in my Ansible inventory every 60 seconds and we certainly don't want to do that.

if I update my Ansible inventory file, the inventory file that this plugin uses, how can I force Rundeck to reload its cache so it's sees the new nodes that just got added via the Ansible inventory file?

Via the Rudeck UI I can "Edit Nodes" and save, not changing anything, and this will trigger a refresh of the node but I'd like to be able to do this programmatically.

There is discussion about this issue here:
https://github.com/rundeck/rundeck/issues/78

and here:
https://github.com/rundeck/rundeck/pull/2380

but I'm not sure if/how pull/2380 relates to the Ansible plugin.

Is "Expose refresh node cache to plugin" implemented in this plugin and if so how do I use this functionality.

Or, I am open to suggestions on how I should be thinking about this if I'm looking at this the wrong way.

Thanks !

**Comment by jimr6007** [comment]
never mind, found the workflow step for reloading the cache

**Comment by mbathe19** [comment]
@jimr6007 can you share the workflow step with me? Have the same problem.
