### ISSUE TITLE
Ansible jobs hanging

### ISSUE THREAD

**Issue by yassineazzouz** [rundeck-plugins/ansible-plugin#29]
Hi Guys,

I recently come across a very weird issue when running long ansible workflow jobs, after a certain time the job hangs and stop logging, I took a look at what the process is doing and it seems that it was stuck trying to write to a PIPE

[root@prssnbd1adm01 ~]# strace -p 11480
Process 11480 attached
write(1, "6.1M\t./hue_server_db_20160512-1"..., 4096

[rundeck@prssnbd1adm01 ~]$ lsof -p 28218
COMMAND PID USER FD TYPE DEVICE SIZE/OFF NODE NAME
ansible-p 28218 rundeck cwd DIR 253,25 4096 20840449 /var/lib/rundeck
ansible-p 28218 rundeck rtd DIR 253,1 4096 2 /
ansible-p 28218 rundeck txt REG 253,17 9032 11902 /usr/bin/python
......
ansible-p 28218 rundeck mem REG 253,17 99158576 4194 /usr/lib/locale/locale-archive
ansible-p 28218 rundeck 0r FIFO 0,8 0t0 35560664 pipe
ansible-p 28218 rundeck 1w FIFO 0,8 0t0 35560665 pipe
ansible-p 28218 rundeck 2w FIFO 0,8 0t0 35560665 pipe
......
ansible-p 28218 rundeck 4r FIFO 0,8 0t0 35560664 pipe
.....
ansible-p 28218 rundeck 7r FIFO 0,8 0t0 35560664 pipe
ansible-p 28218 rundeck 8r FIFO 0,8 0t0 35560664 pipe
ansible-p 28218 rundeck 9r FIFO 0,8 0t0 35560664 pipe
ansible-p 28218 rundeck 10w REG 253,15 17623859 33 /tmp/ansible.log
ansible-p 28218 rundeck 11w REG 253,15 0 45 /tmp/.ansible-lock.16928
ansible-p 28218 rundeck 12r FIFO 0,8 0t0 35560664 pipe
ansible-p 28218 rundeck 13r FIFO 0,8 0t0 35560664 pipe
ansible-p 28218 rundeck 14r FIFO 0,8 0t0 35560664 pipe

I tried to increase the Log output Limit parameter to 1GB but it does not seems to fix the issue. This is probably related to the maximum PIPE in Linux. I'm using centos 6.7 so it should be 64KB I think.

Plus the other weird thing is that logs are not updated dynamically in the UI while the job is running.

Thanks,

**Comment by frozenice** [comment]
What versions are you running (Rundeck, Plugin)?

**Comment by yassineazzouz** [comment]
Hi @frozenice ,

I'm using rundeck 2.6.6, plugin 1.2.2 and ansible 1.9.4

Thanks,

**Comment by frozenice** [comment]
Can you try again with plugin version 1.2.3?

**Comment by yassineazzouz** [comment]
Hi @frozenice , Thanks for the answer, I tried with version 1.2.3 and it seems the jobs are no longer hanging however I still can't see the output times in real time. actually once the job finishes I see all the logs but while the job is running I can't see any logs so I don't really have any clue what the job is doing.

Thanks,

**Comment by frozenice** [comment]
Do you mean you don't see the result of each host as it completes the command (big chunk of output is printed in one go per host) or do you want to see individual lines of your command as they are printed in you command (which isn't supported by Ansible afaik)?

**Comment by frozenice** [comment]
Can you please try the new [v1.2.4](https://github.com/Batix/rundeck-ansible-plugin/releases/tag/1.2.4)? See the [README](https://github.com/Batix/rundeck-ansible-plugin#debugging) on how to enable debugging!

Also see my previous question.

**Comment by angystardust** [comment]
Hi @yassineazzouz , this behavior is caused by python buffering suppressing the output.
As a workaround, you can set this persistent environment variable for the 'rundeck' user
https://coderwall.com/p/d5zqla/unbuffered-output-with-ansible-in-jenkins

P.s.: @frozenice , if my tip works, what about document it on the README?

**Comment by frozenice** [comment]
@angystardust sure, if it helps. Feel free to send a PR when it's confirmed!

**Comment by yassineazzouz** [comment]
Hi @angystardust ,

Thanks lot for the suggestion, I tried with PYTHONUNBUFFERED=1 on v1.2.4 but still no output. Not sure what the issue, for now as a workaround I use a shell job with an ansible-playbook command which logs perfectly fine. I'm not sure what the issue is. Are you guys able to reproduce it ?

Thanks,

**Comment by frozenice** [comment]
@yassineazzouz What exactly are you trying to run? Can you give us an example job as YAML?

**Comment by yassineazzouz** [comment]
Hi @frozenice ,

below a simple job I tested with : 
- hosts: localhost
  tasks:
  - debug: msg="begin"
  - shell: "sleep 15"
  - debug: "first pass"
  - shell: "sleep 15"
  - debug: "second pass"
  - shell: "sleep 15"
  - debug: msg="done"

I got the same issue, the job does not display any logs until it finishes.

I have the PYTHONUNBUFFERED environement variable set to 1 
[rundeck@prssnbd1adm01 platform-scripts]$ echo $PYTHONUNBUFFERED
1
But I'm not sure if it is defined for the running rundeck process, just to make sure, I'm doing the right thing where do you suggest defining it ?

**Comment by angystardust** [comment]
Hi @yassineazzouz , can you please paste the output of this command?
`cat /proc/$(pidof java)/environ`

Anyway, did you exported the PYTHONUNBUFFERED variable in the /etc/rundeck/profile conf file?

**Comment by yassineazzouz** [comment]
Hi @angystardust ,

I have a lot of java processes running, but I guess, this is the one you need:

HOSTNAME=prssnbd1adm01.bigdata.intraxaSHELL=/bin/bashTERM=xtermHISTSIZE=1000PYTHONUNBUFFERED=1QTDIR=/usr/lib64/qt-3.3QTINC=/usr/lib64/qt-3.3/includeUSER=rundeckTMOUT=3600MAIL=/var/spool/mail/rundeckPATH=/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/opt/node/bin:/opt/node/bin:/opt/node/bin:/opt/node/bin:/var/lib/rundeck/binPWD=/var/lib/rundeckLANG=en_US.UTF-8HISTCONTROL=ignoredupsSHLVL=1HOME=/var/lib/rundeckLOGNAME=rundeckQTLIB=/usr/lib64/qt-3.3/libCVS_RSH=sshLESSOPEN=||/usr/bin/lesspipe.sh %sHISTTIMEFORMAT=%F %T G_BROKEN_FILENAMES=1_=/usr/bin/java

It looks indeed that  PYTHONUNBUFFERED=1 is defined and yes I defined it in /etc/rundeck/profile.

Thanks,

**Comment by yassineazzouz** [comment]
Don't you think it is related to this piece of code : 

`    if (!stream) {
      outputFile = File.createTempFile("ansible-runner", "output");
      processBuilder
        .redirectErrorStream(true) // redirect stderr to stdout
        .redirectOutput(outputFile); // redirect to file, stream might block on too much output
    }
    Process proc = processBuilder.start();

```
if (stream) {
  InputStream stdout = proc.getInputStream();
  InputStreamReader in = new InputStreamReader(stdout);
  LineNumberReader lines = new LineNumberReader(in);
  String line;
  StringBuilder sb = new StringBuilder();
  while ((line = lines.readLine()) != null) {
    sb.append(line).append("\n");
    if (listener != null) listener.output(line);
  }
  output = sb.toString();
}`
```

I'm under the impression that rundeck could not find the output log file to display during execution.

**Comment by frozenice** [comment]
Now I know what you mean. :) I updated it to always display the normal Ansible output (except for ad-hoc commands / scripts, which should only print stdout/stderr).

Please take a look at the [new release](https://github.com/Batix/rundeck-ansible-plugin/releases)!

**Comment by yassineazzouz** [comment]
Works perfectly fine, I was actually putting together a PR for it :) 

thank you so much,
