### ISSUE TITLE
Add Key Storage support to Ansible Resource Model Source

### ISSUE THREAD

**Issue by ghost** [rundeck-plugins/ansible-plugin#298]
As outlined in the [Rundeck 3.3.9 Release Notes](https://docs.rundeck.com/docs/history/3_3_x/version-3.3.9.html) (or also see [this issue](https://github.com/rundeck/rundeck/issues/6666)), Rundeck now has support for utilizing the Key Storage feature within Resource Model Node Sources. Would it be possible to add this support to the Ansible Resource Model Source, that way the vault password, SSH password, SSH key file, etc could all be stored safely in Key Storage?

Thanks!

**Comment by martin-gerdes** [comment]
Seconded!

That would be a great help!

**Comment by stuartmaxwell** [comment]
This is an issue for me too. Any chance this is being looked at?

**Comment by arakakimarcelo** [comment]
This is important for me too

**Comment by EmilioMoreno** [comment]
After several hours trying I have found this thread, this is a must for me. Actually I am not able to use rundeck due to this

**Comment by m1hanick** [comment]
I would also give my voice for having this feature.

**Comment by sdtravieso83** [comment]
+1 this.

**Comment by yakhatape** [comment]
Any news about this issue ?

**Comment by ilyavaiser** [comment]
+1 this.  Any news about this issue ?

**Comment by cbarrette-m** [comment]
Any updates on this? This is a very much needed feature to enable our desired workflows.

**Comment by Lusitaniae** [comment]
Looks like there's a PR started but no reviews:
https://github.com/rundeck-plugins/ansible-plugin/pull/336

Would be greatly appreciated if this was looked over

**Comment by stakeconomy** [comment]
+1 this

**Comment by Juanito87** [comment]
This will be a great addition.

**Comment by MegaDrive68k** [comment]
Added, take a look at [this](https://github.com/rundeck-plugins/ansible-plugin/pull/336).
