### ISSUE TITLE
v2_runner_on_failed()  got an unexpected keyword argument 'ignore_errors'

### ISSUE THREAD

**Issue by sly00er** [rundeck-plugins/ansible-plugin#30]
When using Rundeck (2.6.7)  + Ansible (2.0.2) + rundeck-ansible-plugin (1.2.3)

The module "command" is failing with :
MyServerName | FAILED | rc=2 >>[Errno 2] No such file or directory [WARNING]: Failure when attempting to use callback plugin (</usr/lib/python2.7 /site-packages/ansible/plugins/callback/tree.CallbackModule object at 0x26c2fd0>): v2_runner_on_failed() got an unexpected keyword argument 'ignore_errors'

Any idea ?

**Comment by sly00er** [comment]
Apparently, that error is coming from a callback plugin to display output messages.  And probably the rundesk/ansible custom callback plugins is breaking .

**Comment by frozenice** [comment]
Can you please try the new [v1.2.4](https://github.com/Batix/rundeck-ansible-plugin/releases/tag/1.2.4)? See the [README](https://github.com/Batix/rundeck-ansible-plugin#debugging) on how to enable debugging!

"No such file or directory" sounds like Ansible couldn't find MyServerName in your inventory file.

The WARNING sounds like an issue with Ansible, there are no (custom) callback plugins here, it doesn't modify Ansible at all.

**Comment by sly00er** [comment]
Same problem with 1.2.4,  ansible ping working fine on the target server node.

The problem seems it got an unexpected keyword argument
'ignore_errors'

# 

| FAILED | rc=2 >>[Errno 2] No such file or directory
 [WARNING]: Failure when attempting to use callback plugin (</usr/lib/python2.7
/site-packages/ansible/plugins/callback/tree.CallbackModule object at
0x1948b50>): v2_runner_on_failed() got an unexpected keyword argument
'ignore_errors'

**Comment by frozenice** [comment]
This sounds like an incompatibility issue in Ansible, maybe something like ansible/ansible#13646 or ansible/ansible-modules-core#2962. I don't think it's related to this plugin.

Have you tried to enable debug mode as per my README? Maybe you get some more clues this way.

**Comment by lunawesley9** [comment]
This seems to happen with jobs that has issues itself.
but the error message is not very friendly .

For example, the job below has used this ansible plugin, but in the first step it has to run a command first. The command is `sudo` here, which would return the usage instead of doing anything as the command is incomplete. 

the following would be the log: 

```
[workflow] beginExecuteNodeStep(host001): NodeDispatch: com.dtolabs.rundeck.execution.ExecutionItemFactory$4@73caaa52
extraArgs: -u root
tokenized: [-u, root]
Ansible command:
[ansible, all, -m, shell, -a, executable=/bin/bash 'sudo', -t, /tmp/rundeck/ansible-rundeck1063164277677129944, -l, host001, -vvvv, -u, root]
Ansible output:
Using /etc/ansible/ansible.cfg as config file
Loaded callback minimal of type stdout, v2.0
Loaded callback tree of type aggregate, v2.0
<host001> ESTABLISH SSH CONNECTION FOR USER: root
<host001> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r host001 '/bin/sh -c '"'"'mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1465488907.36-69355983102226 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1465488907.36-69355983102226 `"'"'"''
<host001> PUT /tmp/tmpsmGVbz TO /root/.ansible/tmp/ansible-tmp-1465488907.36-69355983102226/command
<host001> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r '[host001]'
<host001> ESTABLISH SSH CONNECTION FOR USER: root
<host001> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt host001 '/bin/sh -c '"'"'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1465488907.36-69355983102226/command; rm -rf "/root/.ansible/tmp/ansible-tmp-1465488907.36-69355983102226/" > /dev/null 2>&1'"'"''
host001 | FAILED | rc=1 >>
usage: sudo [-D level] -h | -K | -k | -V
usage: sudo -v [-AknS] [-D level] [-g groupname|#gid] [-p prompt] [-u user
            name|#uid]
usage: sudo -l[l] [-AknS] [-D level] [-g groupname|#gid] [-p prompt] [-U user
            name] [-u user name|#uid] [-g groupname|#gid] [command]
usage: sudo [-AbEHknPS] [-r role] [-t type] [-C fd] [-D level] [-g
            groupname|#gid] [-p prompt] [-u user name|#uid] [-g groupname|#gid]
            [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-AknS] [-r role] [-t type] [-C fd] [-D level] [-g
            groupname|#gid] [-p prompt] [-u user name|#uid] file ...
 [WARNING]: Failure when attempting to use callback plugin (</usr/lib/python2.7
/site-packages/ansible/plugins/callback/tree.CallbackModule object at
0x20e4a90>): v2_runner_on_failed() got an unexpected keyword argument
'ignore_errors'

Failed: AnsibleNonZero: Ansible exited with non-zero code.
[workflow] finishExecuteNodeStep(host001): NodeDispatch: AnsibleNonZero: Ansible exited with non-zero code.
1: Workflow step finished, result: Dispatch failed on 1 nodes: [host001: AnsibleNonZero: Ansible exited with non-zero code.]
[workflow] Finish step: 1,NodeDispatch
[workflow] Finish execution:  rundeck-workflow-node-first: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [host001: AnsibleNonZero: Ansible exited with non-zero code.]}, Node failures: {host001=[AnsibleNonZero: Ansible exited with non-zero code.]}, status: failed]
[Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [host001: AnsibleNonZero: Ansible exited with non-zero code.]}, Node failures: {host001=[AnsibleNonZero: Ansible exited with non-zero code.]}, status: failed]
Execution failed: 31: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [host001: AnsibleNonZero: Ansible exited with non-zero code.]}, Node failures: {host001=[AnsibleNonZero: Ansible exited with non-zero code.]}, status: failed]
```

**Comment by frozenice** [comment]
Ah, it only happens when the remote command fails and the `-t` option is used, as the plugin does (tried it with Ansible v2.0.1.0).

Upgrading Ansible to v2.1.0.0 fixed it for me. Try upgrading Ansible to the newest version!

Closing as it's not really an issue with the plugin. Feel free to report if it worked for you!
