### ISSUE TITLE
Ansible Resource Model missing "SSH Passphrase for private key"

### ISSUE THREAD

**Issue by rrblocker** [rundeck-plugins/ansible-plugin#300]
In the "Ansible Resource Model Source" there is no way to set the option for the "SSH Passphrase for private key". This option is present in the "Ansible Ad Hoc Node Executor" Project configuration settings as well as in the "Ansible Playbook" and "Ansible Inline Playbook" Job Workflow configuration settings. Having it missing from the "Ansible Resource Model Source" makes it impossible to use the option in the Workflow and Ad Hoc settings, because if a password is set on the ssh key, it cannot be provided to the Resource Model Source, so no nodes are visible.

**Comment by martin-gerdes** [comment]
See also https://github.com/Batix/rundeck-ansible-plugin/issues/298
I think it would make sense to solve these 2 issues together, so the same data, securely saved in the Key Storage, can be used to enable ssh connections in all the Ansible Plugin components.
(Right now we'd have to set up a new ssh keypair without a password, and then save it outside the Key Storage... I'll just wait for an update before we migrate to rundeck instead.)

**Comment by c-erb** [comment]
Strange that this is still not fixed. It is very important if you want to switch to rundeck.

**Comment by florian-asche** [comment]
Security should be #1. This may not be the product for production environment.

**Comment by ltamaster** [comment]
this already exits in the lastest releases
