### ISSUE TITLE
Minimum ansible version

### ISSUE THREAD

**Issue by Julius2342** [rundeck-plugins/ansible-plugin#33]
Ubuntu 14 ships with ansible version 1.5.4. This causes an error when executing gather-hosts.yml :

```
ERROR: run_once is not a legal parameter in an Ansible task or handler
```

You should add a note that minimum ansible version is 1.7.*

**Comment by frozenice** [comment]
Good point, I only started to use Ansible with a later version.

Do you want to submit a PR? :)
