### ISSUE TITLE
Working with virtual environment

### ISSUE THREAD

**Issue by lokly** [rundeck-plugins/ansible-plugin#35]
I use the python virtual environment "virtualenv" where ansible is stored. Sourcing the environment is not the problem, but rundeck lose the environment settings especially the global variable path. 

Is it possible to add a feature, that sources the virutalenv to hold the settings for  ansible? Or did anyone know a solution for this behavior?

**Comment by yassineazzouz** [comment]
Hi @lokly ,
Did you try sourcing the file in /etc/rundeck/profile and restarting rundeck ?

**Comment by lokly** [comment]
Thanks for this hint. I did not source it in the rundeck profile, made it and it works fine! 
Thank you!
