### ISSUE TITLE
Removing file logging and json log parsing

### ISSUE THREAD

**Issue by yassineazzouz** [rundeck-plugins/ansible-plugin#37]
Hi @frozenice ,

I noticed that the jobs try to parse logs to json format after the Job finishes : 
`private void parseOutput() {
    if (type == AnsibleCommand.Playbook && doParseOutput) {
      // TODO not all modules print JSON with -v (e.g. debug), drop all this? it's not used either...
      AnsibleTask curTask = null;

```
  for (String line : output.split("\\r?\\n")) {
    line = line.trim();

    Matcher mTask = pTask.matcher(line);
    if (mTask.find()) {
      curTask = new AnsibleTask();
      results.add(curTask);
      curTask.name = mTask.group(1);
      continue;
    }

    if (curTask == null) continue;

    Matcher mHost = pHostPlaybook.matcher(line);
    if (mHost.find()) {
      AnsibleTaskResult taskResult = new AnsibleTaskResult();
      curTask.results.add(taskResult);

      taskResult.result = mHost.group(1);
      taskResult.host = mHost.group(2);
      String jsonStr = mHost.group(3);
      taskResult.json = new JsonParser().parse(jsonStr).getAsJsonObject();
    }
  }
}
```

  }` 

I think as you noted in your comments not all modules print Json, so from my personal opinion it is not really needed to try to parse logs after the Job finishes, just returning them to stdout will be good enough. For the file logging I beleive this is not needed either since rundeck will always keep a copy of the job logs when it finishes. What do you think ?

**Comment by frozenice** [comment]
Yeah I didn't remove it with the last change directly to think about it again. As you mentioned it doesn't really fit, so I think it can be removed. :)

P.S.: To format multi-line code, surround it with 3 backticks (`) instead of one.
