### ISSUE TITLE
[feature] Can we custom the fact fields that get from ansible ?

### ISSUE THREAD

**Issue by zwxk14** [rundeck-plugins/ansible-plugin#4]
This will make the node details much more useful and readable.

Thanks!

**Comment by frozenice** [comment]
Can you tell me what isn't readable? Is it the amount of facts and you want to limit it to just some?

At the moment the facts are [hardcoded](https://github.com/Batix/rundeck-ansible-plugin/blob/master/src/main/java/com/batix/rundeck/AnsibleResourceModelSource.java#L137), with a bit of name-transformation. I'm not sure what's the best way to make this customizable.

I agree it would be nice to have, but I don't think it can be done in the GUI. Maybe via a properties file, although the syntax would be a bit messy (e.g. the map-like structure as properties, telling it that `ansible_date_time.tz` should be imported as `tz`).

**Comment by zwxk14** [comment]
Sorry, I didn't make myself clear. 

Because I found that i couldn't find the "ipv4 adress" in the node detail page, but it was in the hostname. I think it suppose to be caused by my ansible hosts file format(ansible_ssh_host=ip.adress). Maybe we can do some map or add the official "ansible_default_ipv4.address" as custom filed.

On the other side, ansible support to customize facts that are usually useful and important. but the custom facts will be dropped after collected by the plugin.

I think properties file is good enough if it can be reloaded.

Thanks for your wonderful job for this plugin.

**Comment by frozenice** [comment]
At the moment it's using a hardcoded list of facts (or rather a mapping, to give them a nicer name in Rundeck, see the link above), which I wrote down manually after looking at the default facts that got returned for my hosts.

Importing all facts would be overkill, as there are many which aren't needed, IMO. Doing it automatically would produce some obscure names, too (think about arrays and objects).

A quick PR to add ansible_default_ipv4.address would be cool. ;)

I'll investigate the config file when I have some time.

**Comment by frozenice** [comment]
As noted in #15 local facts would need a smart automatic mapping and configuration anyway, so I guess we'd need:
- automatic mapping of names (e.g. stripping the `ansible_` prefix, local facts get a local_ prefix, replacing dots by underscores if Rundeck doesn't like dots, array handling)
- white- / blacklist
- overrides for specific names / keys

**Comment by foxracle** [comment]
the most wanted feature until now! one more suggestion, IP is not the best choice as the default value of node name because it is not human-readable things while comparing to ansible_nodename or ansible_hostname or ansible_fqdn ;)

**Comment by DerekTBrown** [comment]
See answer here: https://github.com/Batix/rundeck-ansible-plugin/issues/10
