### ISSUE TITLE
No matched nodes while executing playbooks

### ISSUE THREAD

**Issue by zilkanir** [rundeck-plugins/ansible-plugin#41]
system: centos 6.8 x86_64 , ansible-2.1 , rundeck-2.6.8 Batix/rundeck-ansible-plugin v1.3.0

rundeck runs on the same ansible controller host, and i just want to run the playbooks from rundeck interface.

su rundeck -c "ansible all -m ping" , works well, but when i try to run playbooks from rundeck there's an error:

Execution failed: 10: No matched nodes: MultiNodeSelector{nodenames=[localhost]}

in the jobs the node selection is "Execute locally", on the second option "Dispatch to Nodes" there's no hosts on the list. the hosts specified in the ansible playbooks, so i don't really need to specify it to rundeck, am i missing something here? rundeck should run the playbooks on the same host, and the ansible will deploy to the remote systems.

Thanks, Nir.

**Comment by zilkanir** [comment]
libselinux-python installation solved the problem. thanks

**Comment by frozenice** [comment]
As noted in the README. :)
