### ISSUE TITLE
custom facts list / adding nics detailes

### ISSUE THREAD

**Issue by zilkanir** [rundeck-plugins/ansible-plugin#42]
Hi,
is it possible to add/remove ansible facts in nodes facts list?
the most important for now is adding the nics detailes like:

```
    "ansible_default_ipv4": {
        "address": "", 
        "alias": "eth0", 
        "broadcast": "", 
        "gateway": "", 
        "interface": "eth0", 
        "macaddress": "", 
        "mtu": 1500, 
        "netmask": "", 
        "network": "", 
        "type": "ether"
    }, 
```

Many thanks,
Nir.

**Comment by yassineazzouz** [comment]
Hi @zilkanir ,
Currently the list of gathered facts is hard coded but yes it is possible to include extra host facts, I was actually working on something to include all facts returned by ansible gather facts.

**Comment by zilkanir** [comment]
great! thanks.
i will follow,

Best Regards,
Nir.

**Comment by frozenice** [comment]
This is tracked in #4.
