### ISSUE TITLE
Resource Model Source - Permission problem

### ISSUE THREAD

**Issue by ghost** [rundeck-plugins/ansible-plugin#43]
Hi, I have simmilar problem to other users.

I try gather facts with hosts file I have this error in service.log:
`ERROR ExceptionCatchingResourceModelSource: [ResourceModelSource: 2.source (Ansible Resource Model Source), project: test] 
com.dtolabs.rundeck.core.resources.ResourceModelSourceException: Error deleting temporary directory.
...
Caused by: java.nio.file.AccessDeniedException: /tmp/rundeck/ansible-hosts1103819196691470598/data/os1`

When I check permissions of that directory I discovered that ansible-hosts is created by user rundeck, but directory data is created by root user. Other users don't have perrmission to modify directory and that cause error.

I have plugin version 1.3 and I use rundeck user to execute ansible.

Can you Investigate this?

**Comment by yassineazzouz** [comment]
Hi @lordwojtas1991 ,

Can you try deleting it manually then check if you still have the same folder. I suspect that folder to be created before manually by root, in that case it makes since that the AnsibleRunner can not delete it. That folder should be owned by rundeck:rundeck.

**Comment by ghost** [comment]
You were right. I had in my Ansible config "become_user=root" and that was a problem. Now everything is fine.
