### ISSUE TITLE
Inconsistent inventory in Resource Model Source and Jobs

### ISSUE THREAD

**Issue by yassineazzouz** [rundeck-plugins/ansible-plugin#45]
Hi @frozenice ,

I came across an issue when configuring a custom inventory files at the project level, the jobs does not take that into consideration, so the same parameter need to be added in all jobs definition in order for it to work. for instance if I set an extra argument :  '-i /path/to/custom/inventory' in Resource Model Source configuration, the same argument need to be added in all jobs in that project which is kind of confusing since most people will think that what they put in their project configuration (for host gathering) will be used for all Jobs.

I suggest adding a new option for the inventory in "Ansible Resource Model Source" that defaults to empty (/etc/ansible/hosts) then use that same inventory file for all Jobs defined for that project.

What do you think ?

**Comment by frozenice** [comment]
Yeah I noticed that too and postponed it until I figure out how all those configurations in Rundeck work. :) Didn't get around to it yet, documentation is scarce.

I wanted to do this for the debug mode too, but settled for the easier Java system property.

I also couldn't quite decide on which component to add the "project-global" options, as all of them will need to read them.

There is also the problem that you can add multiple resource model sources and I don't know if you can get the resource model for a node, to read the correct options from there.

But let's focus on adding this one option to the resource model source first. We can take another look at this more advanced problem later. :)

**Comment by yassineazzouz** [comment]
Included in release 2.0.0
