### ISSUE TITLE
Working directory configuration option

### ISSUE THREAD

**Issue by inabhi9** [rundeck-plugins/ansible-plugin#47]
I recently got my hands on rundeck and ansible. I could successfully setup the basic job to run ansible playbook using this plugin. I found these two things can be improved
- Project configuration option for specifying inventory file (I guess this issue already reported). Though I manage to get it worked using `-i` flag in extra args input so plugin could generate the node lists. But same inventory file always has be filled while defining job steps. It would be great if plugin automatically takes default args from project configuration or any other better solution.
- Working directory: I couldn't found any way in plugin configuration or rundeck configuration to specify working directory for the job run. So if my playbook is in some random location like `/abc/xyz/opq/site.yml` it could not run successfully. I end up writing angular wrapper which tries to find project root and switch the working directory. (https://gist.github.com/inabhi9/9da3ac8d752f57f162cf7c3b80d450c8)

Thanks for the great work!

**Comment by yassineazzouz** [comment]
Hi @inabhi9 ,

I'm glad you like using the ansible rundeck module :). As you mentioned for the inventory file we are working to make it a global project configuration, so that's already being addressed. For the second issue, I don't really undrestand why you need a root project configuration, you just need to specify the full path of your playbook in the job configuration.

**Comment by inabhi9** [comment]
@yassineazzouz I give the full path in job configuration but the thing is when rundeck runs the job, it sets working directory at something `/var/rundeck/log` and `ansible-playbook` cannot find other roles.

I've multiple ansible project managed with rundeck and this plugin. Each has its own configuration, roles, module, etc..

For eg, One of my ansible project is located at `/opt/abc/xyz` and playbook is `/opt/abc/xyz/site.yml` when rundeck runs the job it executes like this

```
ansible-playbook -i /opt/abc/xyz/inventories/staging.ini /opt/abc/xyz/site.yml` and error raise up

`ERROR! the role 'common' was not found in /opt/abc/xyz/playbooks/listener/roles:/opt/abc/xyz/listener:/etc/ansible/roles

The error appears to have been in '/opt/abc/xyz/playbooks/listener/main.yml': line 4, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - {role: common, tags: ['listener', 'listener:bootstrap']}
      ^ here
```

It's because all path in my ansible projects are relatives and my directory structure is something like this.

```
|- group_var
|- inventories
   |- staging.ini
   |- production.ini
|- playbooks
   |- listener
      |- main.yml
      |- runtest.yml
   |- ...
|- roles
   |- common
   |- listener
   |- ...
|- ansible.cfg
|- site.yml
```

I've created playbook for each role to run various tasks (`main.yml`) and run project test (not asible) because ansible doesn't have feature to run task only if tags specified.

My site.yml contains

```
- include: playbooks/listener/main.yml
- include: playbooks/.../main.yml
- include: playbooks/.../main.yml
```

I can successfully run the job if I'm in the project directory. I don't know if I'm doing it wrong

**Comment by yassineazzouz** [comment]
Hi @inabhi9 ,

What you are trying to do actually does not work. when you execute an ansible script, ansible will always look for the roles in the "roles" folder where the script is located or in /etc/ansible/roles. In your case you are executing site.yml which is including other files under "playbooks/listener", so the script that is really assigning the role is under "playbooks/listener" so ansible will look for the roles folder there. and this actually have nothing to do with the plugin it is just how ansible works.

So I suggest you move your files under /opt/abc/xyz or you can also create a role called listener and use meta to set "common" as a role dependency. But you should not put your playbooks in a sub folder.

Please let me know if that makes sense for you ?

**Comment by inabhi9** [comment]
Hi @yassineazzouz ,

I got your point and that makes sense. I've tried modified the site.yml and given the role and tried running but the problem is, I also have custom ansible configuration file in project directory and ansible cannot find it if executed from other directory. Ansible doesn't have any CLI argument to specify the config file.

So, I think working directory option makes sense. Let me know what do you think.

Thanks!

**Comment by frozenice** [comment]
Should be doable like the project-global inventory option, planned in #45.

**Comment by yassineazzouz** [comment]
Hi @inabhi9 ,

Please check the latest release, it should include what you are looking for.

Thanks,

**Comment by martinbydefault** [comment]
@yassineazzouz I'm looking at the Release 2.0.0 and I only see the project-global inventory option but I can't find a working directory option.  
I'm having the same situation that @inabhi9 explained and since I have my ansible project in /home/rundeck/ansible/, in each execution of a playbook, ansible complains about not finding the ansible.config file. 

It would be great if you can also add the option to set the working directory for each project.

**Comment by stokkie90** [comment]
+1 for setting the working directory, otherwise I can't use this plugin

**Comment by fredleger** [comment]
+1 also that make a lot of sense to me also.
i have repo analyzed by travis-ci that works perfectly fine and make use of a local ansible.cfg file to specify the roles_path.
If i run them it rundeck it will fail for such a reason

**Comment by soar** [comment]
Any news?
