### ISSUE TITLE
While runing ansible ping module in rundeck, I am getting below error

### ISSUE THREAD

**Issue by anochand** [rundeck-plugins/ansible-plugin#48]
FAILED => SSH Error: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password)

**Comment by frozenice** [comment]
You'll need to give us more information, like what you are trying to do, your configuration, and such. Also see the README on how to enable debug mode and post a detailled error log, please.

**Comment by anochand** [comment]
I got it solved by adding the ansible users private key to the rundeck user (/var/lib/rundeck/.ssh). Can I use default ansible user to run rundeck as well ?

**Comment by frozenice** [comment]
I don't know. This is a question for Rundeck itself, not this plugin.
Maybe you can set the user in a config, but I guess you'd need to change all the owners etc. of the Rundeck files, sounds like pain.
