### ISSUE TITLE
How can  we run ansible in rundeck with the alternate config file other that /etc/ansible/ansible.cfg ?

### ISSUE THREAD

**Issue by anochand** [rundeck-plugins/ansible-plugin#49]

**Comment by frozenice** [comment]
[Docs](http://docs.ansible.com/ansible/intro_configuration.html) say to use the `ANSIBLE_CONFIG` environment variable. I don't know off the top of my hat if the env of Rundeck gets passed to the Ansible process. If so, you could set this env var for Rundeck.
Anyhow, we could probably add another project-global option, like #45 for this.

**Comment by yassineazzouz** [comment]
right, you can still pass the environment variable to rundeck by defining it in /etc/rundeck/profile it will get passed to all child processes.

**Comment by yassineazzouz** [comment]
Hi @anochand , closing this. please let us know if you still have issues defining the env vars in rundeck. You can also post a question/issue in rundeck project github if you need more input on this.

**Comment by bzlowrance** [comment]
This worked for me

 project.ansible-config-file-path=/mypath/my.cfg
