### ISSUE TITLE
After many jobs were done, got error: "Too many open files" 

### ISSUE THREAD

**Issue by zwxk14** [rundeck-plugins/ansible-plugin#5]
## The error log

> 2016-03-23 11:28:24,041 [Thread-488] ERROR com.dtolabs.rundeck.core.execution.workflow.steps.node.NodeStepPluginAdapter - Error executing node step.
> com.dtolabs.rundeck.core.execution.workflow.steps.node.NodeStepException: Error running Ansible.
>         at com.batix.rundeck.AnsibleModuleNodeStep.executeNodeStep(AnsibleModuleNodeStep.java:32)
>         at com.dtolabs.rundeck.core.execution.workflow.steps.node.NodeStepPluginAdapter.executeNodeStep(NodeStepPluginAdapter.java:106)
>         at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeNodeStep(ExecutionServiceImpl.java:149)
>         at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:116)
>         at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:58)
>         at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.dispatchToNodes(ExecutionServiceImpl.java:177)
>         at com.dtolabs.rundeck.core.execution.workflow.steps.NodeDispatchStepExecutor.executeWorkflowStep(NodeDispatchStepExecutor.java:66)
>         at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeStep(ExecutionServiceImpl.java:116)
>         at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWFItem(BaseWorkflowStrategy.java:225)
>         at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflowItemsForNodeSet(BaseWorkflowStrategy.java:303)
>         at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflowItemsForNodeSet(BaseWorkflowStrategy.java:258)
>         at com.dtolabs.rundeck.core.execution.workflow.StepFirstWorkflowStrategy.executeWorkflowImpl(StepFirstWorkflowStrategy.java:79)
>         at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflow(BaseWorkflowStrategy.java:182)
>         at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowStrategy$DispatchedWorkflow.dispatch(NodeFirstWorkflowStrategy.java:383)
>         at com.dtolabs.rundeck.core.execution.dispatch.ParallelNodeDispatcher$1.call(ParallelNodeDispatcher.java:179)
>         at com.dtolabs.rundeck.core.cli.CallableWrapperTask.execute(CallableWrapperTask.java:52)
>         at sun.reflect.GeneratedMethodAccessor2128.invoke(Unknown Source)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:606)
>         at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
>         at org.apache.tools.ant.Task.perform(Task.java:348)
>         at org.apache.tools.ant.taskdefs.Parallel$TaskRunnable.run(Parallel.java:435)
>         at java.lang.Thread.run(Thread.java:745)
> **Caused by: java.io.IOException: Cannot run program "ansible": error=24, Too many open files**
>         at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
>         at com.batix.rundeck.AnsibleRunner.run(AnsibleRunner.java:124)
>         at com.batix.rundeck.AnsibleModuleNodeStep.executeNodeStep(AnsibleModuleNodeStep.java:30)
>         ... 22 more
> Caused by: java.io.IOException: error=24, Too many open files
>         at java.lang.UNIXProcess.forkAndExec(Native Method)
>         at java.lang.UNIXProcess.<init>(UNIXProcess.java:186)
>         at java.lang.ProcessImpl.start(ProcessImpl.java:130)
>         at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
>         ... 24 more
## Analyze

Rundeck run with user "rundeck" ,

**ulimit -a**

> core file size          (blocks, -c) 0
> data seg size           (kbytes, -d) unlimited
> scheduling priority             (-e) 0
> file size               (blocks, -f) unlimited
> pending signals                 (-i) 15236
> max locked memory       (kbytes, -l) 64
> max memory size         (kbytes, -m) unlimited
> **open files                      (-n) 1024**
> pipe size            (512 bytes, -p) 8
> POSIX message queues     (bytes, -q) 819200
> real-time priority              (-r) 0
> stack size              (kbytes, -s) 10240
> cpu time               (seconds, -t) unlimited
> max user processes              (-u) unlimited
> virtual memory          (kbytes, -v) unlimited
> file locks                      (-x) unlimited

The error can be fixed by increasing "max open files", but I think maybe something wrong with closing the file descriptor.

**lsof -p 2017**

> java    2107 rundeck  380r   REG              253,0     8338  270599 /tmp/ansible-hosts1374348696218756678/data/xxxxx (deleted)
> java    2107 rundeck  381r   REG              253,0     6462  270656 /tmp/ansible-hosts1374348696218756678/data/xxxxx (deleted)
> java    2107 rundeck  382r   REG              253,0     9621  270650 /tmp/ansible-hosts1374348696218756678/data/xxxxx (deleted)
> java    2107 rundeck  383r   REG              253,0     7892  270646 /tmp/ansible-hosts1374348696218756678/data/xxxxx (deleted)
> java    2107 rundeck  384r   REG              253,0     6538  270626 /tmp/ansible-hosts1374348696218756678/data/xxxxx (deleted)
> java    2107 rundeck  385r   REG              253,0     6252  270638 /tmp/ansible-hosts1374348696218756678/data/xxxxx (deleted)
> java    2107 rundeck  386r   REG              253,0     6538  270627 /tmp/ansible-hosts1374348696218756678/data/xxxxx (deleted)
> java    2107 rundeck  387r   REG              253,0     6944  270634 /tmp/ansible-hosts1374348696218756678/data/xxxxx (deleted)
> java    2107 rundeck  388r   REG              253,0     6400  270617 /tmp/ansible-hosts1374348696218756678/data/xxxxx (deleted)
> java    2107 rundeck  389r   REG              253,0     6254  270648 /tmp/ansible-hosts1374348696218756678/data/xxxxx (deleted)
> java    2107 rundeck  390r   REG              253,0     6500  270658 /tmp/ansible-hosts1374348696218756678/data/xxxxx (deleted)
> java    2107 rundeck  391r   REG              253,0     6533  270633 /tmp/ansible-hosts1374348696218756678/data/xxxxx (deleted)
> java    2107 rundeck  393r   REG              253,0      461 1572615 /tmp/ansible-hosts5556455135585139371/AnsibleDev (deleted)
> java    2107 rundeck  395r   REG              253,0      383 1572619 /tmp/ansible-hosts5209006839202653699/AnsibleDev (deleted)
> java    2107 rundeck  397r   REG              253,0      375 1572621 /tmp/ansible-hosts1751269568005936368/AnsibleDev (deleted)

It seems that many deleted files was not closed by rundeck progress?

Thanks!

**Comment by frozenice** [comment]
Can you try the [latest release](https://github.com/Batix/rundeck-ansible-plugin/releases)? I added some `close()` calls.

**Comment by zwxk14** [comment]
The 1.0.2 version have fixed the issue.

Thanks!
