### ISSUE TITLE
can't execute commands on the ansible nodes

### ISSUE THREAD

**Issue by Ma-Jing** [rundeck-plugins/ansible-plugin#50]
I have created a project called "ansible_test", the Ansible Resource Model Source configure is below:
- leave blank about "Limit Targets".
- Extra Arguments is "-i /home/test/ansible_test/"，ansible inventory file is under the ansible_test

rundeck can discovery the inventory host，but when I execute commands，it complain with "Using /etc/ansible/ansible.cfg as config file Failed: AnsibleError: ERROR! Specified --limit does not match any hosts"

I stuck here, thanks for your help!

sorry for my poor english.

**Comment by frozenice** [comment]
See #45 for a planned fix.
