### ISSUE TITLE
Running Ansible and Rundeck on separate hosts

### ISSUE THREAD

**Issue by chelming** [rundeck-plugins/ansible-plugin#52]
I have Ansible and Rundeck running on separate hosts. How do I tell the plugin where the Ansible host is? Is this even possible?

**Comment by frozenice** [comment]
The plugin just spawns Ansible processes under the Rundeck user. There is no support for a remote Ansible and I can't imagine how this could work.
If anyone has good ideas on this, feel free to post them!

**Comment by ivanelson** [comment]
Then the rundeckd server and Ansible and my playbooks need to stay on the same server. :(
