### ISSUE TITLE
Can I make this work Rundeck Ansible for below scenario

### ISSUE THREAD

**Issue by sgunnala** [rundeck-plugins/ansible-plugin#54]
Question : We have a ansible setup to deploy multiple applications and each application in inventory has upto 10 servers(parallel execution) using playbook for each app. Can I run multiple playbooks parallel(i.e multiple apps parallel) to reduce my deploy time using rundeck and ansible plugin.

**Comment by frozenice** [comment]
Not really a question for this plugin, but for Rundeck in general. You might want to try asking on the mailing list.
I know Rundeck has some support for this (in form of dependent jobs), but I'm no expert on Rundeck. :)
Mailing list is here: https://groups.google.com/forum/#!forum/rundeck-discuss
