### ISSUE TITLE
Rundeck failing execution of ansible commands/playbooks

### ISSUE THREAD

**Issue by Delizald** [rundeck-plugins/ansible-plugin#55]
Hello all, i know it is possible to use rundeck as an interface to ansible, however i'm having a problem where execution of ansible via rundeck fails.
I am using the ansible-plugin for rundeck to execute playbooks/modules but no matter what i try the execution is not successful as it complains about the node "is not reachable through ssh".

i'm suspecting this is because my localhost is executing the ansible commands as the rundeck user (even if i specify my username and ssh keys in the ansible host file).

I know it's probably a dumb question but i'm fairly new to rundeck+ansible. but is there a way i can install the rundeck user in my node and use the ssh keys its using? Or any tips or guides i can use to use rundeck+ansible?

 Here's an example output i'm getting if i run "ansible all -m ping" command from rundeck:

12:59:26    localhost   Using /etc/ansible/ansible.cfg as config file
12:59:26        <node1> ESTABLISH SSH CONNECTION FOR USER: elizaldd
12:59:26        <node> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/home/elizaldd/.ssh/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=elizaldd -o ConnectTimeout=10 -o ControlPath=/var/lib/rundeck/.ansible/cp/ansible-ssh-%h-%p-%r node1 '/bin/sh -c '"'"'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python && sleep 0'"'"''
12:59:26        node1 | UNREACHABLE! => {
12:59:26            "changed": false, 
12:59:26            "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", 
12:59:26            "unreachable": true
12:59:26        }

And this is the output if run the same command from the command line:

Using /etc/ansible/ansible.cfg as config file
<node1> ESTABLISH SSH CONNECTION FOR USER: elizaldd
<node1> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/home/elizaldd/.ssh/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=elizaldd -o ConnectTimeout=10 -o ControlPath=/home/elizaldd/.ansible/cp/ansible-ssh-%h-%p-%r node1 '/bin/sh -c '"'"'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python && sleep 0'"'"''
node1 | SUCCESS => {
    "changed": false,
    "invocation": {
        "module_args": {
            "data": null
        },
        "module_name": "ping"
    },
    "ping": "pong"

**Comment by Delizald** [comment]
I already tried the instructions in the requirements section of the ansible-plugin github page "If it complains, chances are that your rundeck $HOME directory isn't writable by Rundeck, fix it with e.g. chown rundeck /var/lib/rundeck (see this issue)"

**Comment by frozenice** [comment]
Rundeck launches Ansible under its user (i.e. `rundeck`). Whatever options you specify inside Rundeck don't change that. I guess your `rundeck` user can't access all required files that Ansible needs.
Have you tried running this command from the README on your shell (as root)?
`su rundeck -s /bin/bash -c "ansible all -m ping"`

**Comment by Delizald** [comment]
I managed to get this working thanks to Peter's suggestion (https://groups.google.com/forum/#!topic/rundeck-discuss/y-EBftuwP0s). Even if it's not optimal i managed to run ansible commands/playbooks

**Comment by frozenice** [comment]
With the proper configuration it would also work without sudo. ;)
