### ISSUE TITLE
Colorful output for Ansible logs

### ISSUE THREAD

**Issue by qk4l** [rundeck-plugins/ansible-plugin#58]
Hi,

Have you though  about color for Ansible output?
This feature was implemented in Rundeck 2.1.2 but now users should provide additional variable to make it works with Ansible - `ANSIBLE_FORCE_COLOR=true`.

It would be nice to have it out of box.

**Comment by yassineazzouz** [comment]
Hi @qk4l ,

I agree that's a nice feature, did you try adding the environment variable in /etc/rundeck/profile ? you can just add `export ANSIBLE_FORCE_COLOR=true` then restart rundeckd, Honestly I didn't work with ansible 2.1 yet so not sure how it will get displayed in the UI, but at least that will get the environment variable defined for your ansible processes.

**Comment by qk4l** [comment]
>  did you try adding the environment variable in /etc/rundeck/profile 

Yes, I did it and have color output. 

![rundeck_ansible_color](https://cloud.githubusercontent.com/assets/8394059/18959993/27de8da2-8679-11e6-845c-c3c37f6840f6.png)

**Comment by yassineazzouz** [comment]
Great, glad that worked for you.

**Comment by jackiehope** [comment]
Hi，@qk4l
I add `export ANSIBLE_FORCE_COLOR=true` in /etc/rundeck/profile,I also have rundeckd restarted。But,I didn't have color output。there is my package version：
```
$ rpm -qa | egrep "ansible|rundeck"
rundeck-config-2.6.11-1.23.GA.noarch
ansible-2.1.2.0-1.el7.noarch
rundeck-2.6.11-1.23.GA.noarch
rundeck-repo-4-0.noarch
```

**Comment by jackiehope** [comment]
@qk4l 
Finally, I figure out this by adding `force_color = 1` in ansible config file。

**Comment by unacceptable** [comment]
Hey, it is also worth noting that this works when executing ansible from a null_resource in terraform.

```
resource "null_resource" "ansible_exec" {
    provisioner "local-exec" {
        command = "${file("local-exec.sh")}"
    }
}
```

```
08:04 MacOS: Terraform/ $ tail local-exec.sh 
    done &&
        sleep 10; # give python a few seconds to install
}

exec_ansible(){
    cd ../Ansible;
    ANSIBLE_FORCE_COLOR=true ansible-playbook database.yml;
}

main;
08:04 MacOS: Terraform/ $
```

@qk4l I am pretty sure you saved me from eye cancer.  Thanks!

**Comment by harmanbirdi** [comment]
@ScriptMyJob - Just landed on this page while searching for terraform and ansible. I am trying to have my ansible playbook execute just once for 'n' instances that I create using terraform, but it runs once for each instance created.

Looking at your solution of using a file, I was wondering if it runs just once, or still once per aws resource created.  Right now, if I execute `terraform plan` after making the changes, it still
reports that it will run multiple times.

```
null_resource.coper_provisioner[1]: Refreshing state... (ID: 160278730961747902)
null_resource.coper_provisioner[0]: Refreshing state... (ID: 6987200565147415266)
null_resource.coper_provisioner[2]: Refreshing state... (ID: 3866385660077467001)
```

Could you please let me know, if you have managed to have just one run for the playbook after all
instances have been created and are available? I would really appreciate it.

Thanks.
