### ISSUE TITLE
feature: add support to add a tag per resourceModel

### ISSUE THREAD

**Issue by UnsignedLong** [rundeck-plugins/ansible-plugin#59]
Hi,

given a rundeck project using multiple ansible inventory resource model sources it would be great to add a tag to the resource configuration which is added to every host discovered by the model.

This feature give users the ability  to add - for example - a dev and a prod environment (inventory)  to the same project, set the environment name as a tag in the resource configuration and filter the nodes to only get "prod" or "dev" ones.

**Comment by frozenice** [comment]
Merged and released as v1.4.0, thanks!
