### ISSUE TITLE
FIxed

### ISSUE THREAD

**Issue by opsroller** [rundeck-plugins/ansible-plugin#61]

**Comment by opsroller** [comment]
Forgot one more thing, NO DOCUMENTATION?

**Comment by opsroller** [comment]
Excuse my ignorance, now I see what was happening. This is solely a lack of clean documentation. The problem encountered has to do with which module you use during the Job. In my case I was using the Node executor instead of using the Workflow one.

**Comment by yassineazzouz** [comment]
Hi @opsroller ,

Glad it works for you, sorry I have been away for while so couldn't help you earlier with your issue. I'm will be working on making it simpler and more convenient for users. Thank you anyway for reporting these issues, although I do not agree with your comments.

Thanks,
