### ISSUE TITLE
Encrypted keys in key storage

### ISSUE THREAD

**Issue by lwhitworth** [rundeck-plugins/ansible-plugin#62]
I have my private key in "Key Storage" in Rundeck, and Rundeck itself is configured to use encryption as per http://rundeck.org/docs/plugins-user-guide/bundled-plugins.html#jasypt-encryption-plugin.  This means there's no unencrypted copy of the private key on the host for Ansible to be pointed to for SSH authentication.

Is there any way at all that this plugin can bridge that gap?  I've read the docs and given it a go, but it is failing to connect via ssh:
"fatal: [hostname.domain.com]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}"
And (rightly so) running "su rundeck -s /bin/bash -c "ansible all -m ping"" fails as I'd expect.

**Comment by yassineazzouz** [comment]
Hi @lwhitworth , Are you using --private-key parameter in your job configuration arguments ?

**Comment by yassineazzouz** [comment]
Hi @lwhitworth ,

This should be fixed in release 2.0.0

Thanks,

**Comment by lwhitworth** [comment]
Sorry, just seen your comments.  Apologies for not replying.  Many thanks for fixing, appreciated.
