### ISSUE TITLE
Add context variables support for job steps definition

### ISSUE THREAD

**Issue by GrinGrin** [rundeck-plugins/ansible-plugin#64]
Hi,

It would be really useful to be able to use [context variables](http://rundeck.org/docs/manual/jobs.html#context-variables) in the job steps definitions like ${job.project}, ${job.name} and so on.
Not all context variables are needed as most of them are defined by Ansible facts, but at least the job.*

I'm trying to configure a generic job that can run a playbook stored in the project folder (under /var/rundeck/projects/<project_name>/playbooks) I can duplicate to add now playbooks when needed and such variables would be really useful !

**Comment by yassineazzouz** [comment]
IHi @GrinGrin ,

I assume, you mean accessing the context variables inside your ansible script ? I agree but that will be a bit tricky to add since the variables need to be added to passes to ansible itself.

**Comment by GrinGrin** [comment]
Hi @yassineazzouz ,

I mean using context variables like `${job.project}` to compose a dynamic path to the playbook. Currently Rundeck say the path is not valid if I set something like `/var/rundeck/project/${job.project}/playbooks/something.yml` even if the path, when manually expanded  with the project name, exists on the Rundeck server.

You can see in the screenshot below that I already use this variable in the previous step to create a script going to the desired path and make a git pull before using the playbooks

![2016-09-29_18h17_21](https://cloud.githubusercontent.com/assets/15949215/18962591/c370d4ee-8671-11e6-8793-dc4fe057e4ac.png)

**Comment by yassineazzouz** [comment]
Hi @GrinGrin ,

Ok, I see what you mean, I'm actually working on an almost full rewrite of the plugin code, that I will be available soon hopefully, and will include that.

Thanks,

**Comment by yassineazzouz** [comment]
Hi @GrinGrin ,

This should be fixed in release 2.0.0

Thanks,
