### ISSUE TITLE
Strange behavior with Import / Export on Ansible plugin 

### ISSUE THREAD

**Issue by fossouo** [rundeck-plugins/ansible-plugin#65]
Hello,

i faced an issue that got finally solved with the help of @yassineazzouz. 

I have two instance of Rundeck, the first instance use rundeck as user and the second use rundeck-project as user. 

For some reasons i had to export from the first instance a project and import it in the second instance. 
Till here no problem when i change the path of the YML inside the second instance as i have a different user (/var/lib/rundeck-projects/projects//.....yml) i got this error : {2=Dispatch failed on 1 nodes: [localhost: AnsibleNonZero: Error running Ansible Node Step.]}, Node failures: {localhost=[AnsibleNonZero: Error running Ansible Node Step.]}, flow control: Continue, status: failed]. 

Finally the way to resolve it was to recreate the job in the second instance.

Hope this is something that can be fixed or will help someone else.

Regards 

DF

**Comment by yassineazzouz** [comment]
Thanks @fossouo for sharing this, Exporting and Importing projects is not always straightforward: 
- The paths of the exported and imported projects need to match 
- If your configuration is referencing some keys in the storage path they need to be created manually or adjusted in the Exported file.
