### ISSUE TITLE
limit does not match any hosts

### ISSUE THREAD

**Issue by zwxk14** [rundeck-plugins/ansible-plugin#70]
My environment:
- Ansible 2.x
- ansible-plugin-2.0
- CentOS6.8

When I want to run some job with matched nodes, it return with this error

> Using /etc/ansible/ansible.cfg as config file
> ERROR! Specified --limit does not match any hosts
> ERROR: Ansible execution returned with non zero code.
> Execution failed: 2543: [Workflow result: , step failures: {1=AnsibleNonZero: ERROR: Ansible execution returned with non zero code.}, status: failed]

I thought this must be cause of my inventory settings:
- my plugin settings

> resources.source.1.config.ansible-inventory=/opt/rundeck/tmp
- my ansible settings

> inventory = /etc/ansible/hosts/zabbix

the nodes in /etc/ansible/hosts/zabbix ware not the same in /opt/rundeck/tmp, so i got the errors.

When I custom inventory settings,  the reasonable expectations is the default inventory setings in ansible.cfg will not take effect.

**Comment by nexusvista** [comment]
Hi, when you are on the Nodes tab of Rundeck, did you see any hosts? The plugin should automatically convert your Ansible hosts file to resources.xml.

**Comment by zwxk14** [comment]
@nexusvista 

Yes, I can see the expectantly hosts that defined in /opt/rundeck/tmp in Nodes tab, but when I run the job and choose the matched nodes,  I got the error:

> --limit does not match any hosts

I thought the plugin run jobs with the "--limit" option of ansible, so if the nodes are not in the default inventory of ansible setting, it will get the error.

**Comment by yassineazzouz** [comment]
Hi @zwxk14 ,

Not sure what are you asking, if you specify an inventory in the Resources Model, it will overwrite the one in your ansible configuration, if you don't specify one the one in your ansible.cfg configuration will be used /etc/ansible/hosts/zabbix in your case. 
Keep in mind that `resources.source.1.config.ansible-inventory=/opt/rundeck/tmp` does apply only for the Resources Model, if you want all your jobs inside a project to use that same configuration, you should add : `project.ansible-inventory=/opt/rundeck/tmp` in your project configuration file.

**Comment by zwxk14** [comment]
@yassineazzouz,

Thanks for your explain. 
I was a little confused that can not find anywhere to specify the project nodes in 'Configure Project' interface. I'm clear now.

But on an intuitive level, if you add a project and define nodes resource,  you will think the jobs in the project will be ran with the nodes choosed from resource model.

Thanks for your help again!
