### ISSUE TITLE
"Extra Ansible arguments" are not passed to execution

### ISSUE THREAD

**Issue by shoelzle** [rundeck-plugins/ansible-plugin#73]
Hello,

For a rundeck job I added a workflow step to run an Ansible Playbook.
In the definition of the workflow step there's an option called "Extra Ansible arguments" which I guess is supposed to add additional command line arguments to the ansible-playbook execution.

However, if I set any value in as "Extra Ansible arguments" the extra arguments are not passed to the ansible-playbook execution.

Rundeck version: 2.6.8
rundeck-ansible-plugin version: 2.0.1

**Comment by AlexZolotarenko** [comment]
I can confirm the same behavior. 
Do not know if this exactly correct but I managed to get this working with diff attached ( It also fixes bug with become password ) 

[rundeck_ansible_2.0.1_diff.txt](https://github.com/Batix/rundeck-ansible-plugin/files/548565/rundeck_ansible_2.0.1_diff.txt)

**Comment by shoelzle** [comment]
@AlexZolotarenko I confirm your patch is working, many thanks !

**Comment by yassineazzouz** [comment]
Hi @shoelzle , thanks for reporting this. Agree @AlexZolotarenko that should fix the issue, I will include this in the next release.

Thanks,

**Comment by yassineazzouz** [comment]
Hi @shoelzle ,
This issue should be fixed in release 2.0.2.
Thanks,

**Comment by shoelzle** [comment]
This is fixed in 2.0.2, thanks
