### ISSUE TITLE
how to prevent  outputing message like "Using /etc/ansible/ansible.cfg as config file"

### ISSUE THREAD

**Issue by jackiehope** [rundeck-plugins/ansible-plugin#78]
when I running ansible ad-hoc command or jobs，I always get this annoying message “Using /etc/ansible/ansible.cfg as config file”。But I did not recive this this message when I using ansible in commandline。
My log level：
```
loglevel.default=INFO
```

**Comment by DerekTBrown** [comment]
This is bundled in with the `-v` settings we need to print the options passed to each module.  I don't think there is a way to suppress the warning without also suppressing other needed variables.  If this is mission-critical and you would like to submit a PR, feel free to reopen.
