### ISSUE TITLE
Speeding Up AWS Inventory

### ISSUE THREAD

**Issue by rilindo** [rundeck-plugins/ansible-plugin#8]
I found that it takes quite a while for Rundeck to pull a list nodes through Ansible. It seems that when you do pull a list of nodes, the ansible command gathers most of the facts during the process.
- Use Rundeck as a the inventory source, since it appears to be able to generate a list of nodes far more quickly.
- Also, try to read off the fact_cache (this requires that fact_cache be enabled first, though)before failing back to pulling facts from the AWS instances.

**Comment by frozenice** [comment]
You can use another plugin as the resource model source, the node executor / file copier / etc. just passes the node name to Ansible. As long as that is something Ansible can understand, it should work.

I'm not familiar with the fact cache, is there something the plugin needs to do or is it just something you configure in Ansible? Of course if you don't use Ansible for your resource model source, the facts won't be used anyway.

**Comment by rilindo** [comment]
It is something you can configure in ansible, inside ansible.cfg:

http://jpmens.net/2015/01/29/caching-facts-in-ansible/

**Comment by frozenice** [comment]
So is there still a problem if you use the AWS plugin as the resource model source and the Ansible plugin for execution / file copy? Facts won't be gathered then.

**Comment by frozenice** [comment]
Closing for now.
