### ISSUE TITLE
asnible-playbook  execution with ansible plugin 2.0.2 and rundeck 2.6.9 comes up with an empty Node summary 

### ISSUE THREAD

**Issue by lucecca** [rundeck-plugins/ansible-plugin#80]
Hi,
after executing an ansible playbook from rundeck the Summary tab of Node summary section does not update the complete, failed, incomplete, not started counters at all.
Here below an image documenting this description
![selection_692](https://cloud.githubusercontent.com/assets/22647182/20025695/4186ec2e-a2f1-11e6-9841-b7b702a21c78.png)

Any how checking the Log Output tab I can see the raw ansible output of my playbook.

![selection_693](https://cloud.githubusercontent.com/assets/22647182/20025709/7292962e-a2f1-11e6-8296-07c8def25613.png)

Is there some config parameter that has to be tuned in order to update properly the counters?

Regards

**Comment by aarlint** [comment]
I'm experiencing this.  @lucecca have you found a solution?

**Comment by lucecca** [comment]
@aarlint up to now no.

**Comment by angrynrd** [comment]
Is it possible because this is a workflow step, which runs only once per job and not on every node? As far as I understand rundeck, thats the way workflow steps are supposed to work, trigger an action which is not node specific. Is there a specific reason why the node step was removed in v2?

**Comment by m4dm4rtig4n** [comment]
I have same problem :/
- ansible 2.3.0
- Rundeck 2.7.1-1

**Comment by mrala** [comment]
Has anyone found a workaround or fix this?

**Comment by linlinas** [comment]
+1 same for me

**Comment by linlinas** [comment]
Is there any chance to provide workflow support for ansible tasks included in the playbook executed via rundeck ansible plugin?
Currently for ansible plugin, I am seeing only logout put in verbose mode with no workflow at all.

**Comment by DerekTBrown** [comment]
Unfortunately this isn't something we can do.  @linlinas was correct- a workflow step only executes once, and is therefore not counted against nodes.  We couldn't do this without editing rundeck core.

**Comment by paulholden** [comment]
I've just come across the same problem - seems the discussion has moved to #159 & #139 now...
