### ISSUE TITLE
WIndows/winrm support?

### ISSUE THREAD

**Issue by absolutejam** [rundeck-plugins/ansible-plugin#82]
Is this compatible with windows nodes? I notice that all of the ansible options reference SSH only.

Is there a possible workaround or potential to support Windows?

**Comment by absolutejam** [comment]
For now I'm just running local `ansible-playbook` commands on my Rundeck container, but it would be great to have Windows servers included in this in the future.

As an aside, do the servers not show up as a node if they are uncontactable? Before I realised that winrm wasn't supported, I tried to use the Ansible resource type and I noticed that when my Rundeck process starts, it tries to contact all of my nodes, but fails because it can't authenticate with them.

**Comment by absolutejam** [comment]
I've noticed some more movement on this project. I'm going to have a play tonight, but is there anything official in this side that can be commented on? I'd be happy to add a PR for documentation, or even rudimentary changes to the plugin (I can learn Java in a day right?!) if it could get some Windows authentication features added. Ping @frozenice @yassineazzouz

**Comment by DerekTBrown** [comment]
@absolutejam definitely interested in finding out more (I am new to the project, and also have a number of Windows devices I would like to support).  I haven't done any testing of this (will in the next few days), but cant see any reason why the native Ansible Windows modules wouldn't work.

All this plugin is doing is kicking off a playbook, so as long as your authentication options are set in the inventory, and you are using the Windows Modules, I imagine it will work.

What changes did you have in mind?

**Comment by DerekTBrown** [comment]
@absolutejam looks like there is an existing PR here: 

https://github.com/Batix/rundeck-ansible-plugin/pull/112/files

Will be reviewing that later this week.  Closing this issue as it is redundant.
