### ISSUE TITLE
is there a way for specify path to ansible.cfg in project settins?

### ISSUE THREAD

**Issue by nnovikov** [rundeck-plugins/ansible-plugin#83]
Huh?

**Comment by yassineazzouz** [comment]
Hi @nnovikov ,
nope, however you can customize the ~/.ansible.cfg for the rundeck user.

**Comment by bfidelin** [comment]
You can specify the options ANSIBLE_CFG as environment variable at the job. It was very helpful for me.

**Comment by jackiehope** [comment]
@bfidelin can you give an example on how to use ANSIBLE_CFG as environment variable, I didn't figure this out。thank you very much!

**Comment by bfidelin** [comment]
I put this on my job's definiton
It is just an option. below the extract of job's definition in Yaml
 options:
  - description: /mypath/ansible_job/ansible.cfg
    enforced: true
    name: ANSIBLE_CONFIG
    values:
    - /mypath/ansible_job//ansible.cfg

**Comment by DerekTBrown** [comment]
@bfidelin seems to have answered this already.  Closing.
