### ISSUE TITLE
Installing the Ansible Plugin into Rundeck / three questions

### ISSUE THREAD

**Issue by Kiran57** [rundeck-plugins/ansible-plugin#84]
I am using the installation directions.  But I am not sure on three aspects.  Before I get too far into this process that I do not understand, I have questions on these aspects.  I am using Rundeck 2.7.1.1.

For the 'Choose "Ansible Resource Model Source"' step, how do I do this?  I choose the directory path where I placed the Ansible plugin.  Is this correct?

For the "Ansible Ad-Hoc Node Executor" as the default node executor step, how do I do this?   I see no where to do this.

For the "Ansible File Copier" as the default node executor step, how do I do this?  I see SSH Key FIle Path, and other SSH settings.

**Comment by yassineazzouz** [comment]
Hi @Kiran57 ,

I'm not really sure I understand what you are asking, this is probably more a rundeck usage question. When you create a project you need to add an ansible resource model and configure it (note that you can have multiple node executors). for the node executor and File Copier you just check radio button next to the input that put the configuration.

**Comment by iam0ky** [comment]
Hi @Kiran57,

For the Ansible Resource Model source responds to where the inventory file is and so you should not choose the Ansible plugin path.

**Comment by DerekTBrown** [comment]
More documentation coming.  Closing issue.
