### ISSUE TITLE
using the rundeck keys path for Ansible Resource Model Source

### ISSUE THREAD

**Issue by caphrim007** [rundeck-plugins/ansible-plugin#87]
Hello,

I noticed that one can use the Key storage when creating workflow steps, but not when setting up the Ansible Resource Model Source from inventory. The Source asks for a "File Path to the SSH Key to use" and if I use the key path that Key storage provides me with, it is unable to find it.

I use the same keys with both the inventory and the actual steps, so is it possible to specify the path from a Key storage selection when setting up the Model Source as it is when creating a workflow step?

**Comment by yassineazzouz** [comment]
Hi @caphrim007 ,

Unfortunately this is not allowed by rundeck, there is no interface to access the Key Storage from the Resource Model, so you need to use a simple password.

**Comment by caphrim007** [comment]
@yassineazzouz ok! thanks for clarifying that for me! I'm new to rundeck and didn't know if that were possible or not. I can work with that answer though. thanks!
