### ISSUE TITLE
Manage ansible.cfg through Rundeck

### ISSUE THREAD

**Issue by rilindo** [rundeck-plugins/ansible-plugin#9]
It may be useful for an administrator to be able to manage the ansible.cfg from the rundeck interface. This allow ansible.cfg to be updated without any potential for error (e.g. typos or bad formatting).

**Comment by frozenice** [comment]
This is out of scope for this plugin, but I guess you could create a job in Rundeck that does that, something like this:
- option to enter the contents of the config file
- execute a script to create a temp file with the contents
- run ansible with this temp config file to validate the syntax or something
- move the temp file in place of the real config file
