### ISSUE TITLE
Rundeck don't load group_vars & host_vars ?

### ISSUE THREAD

**Issue by m4dm4rtig4n** [rundeck-plugins/ansible-plugin#90]
Hi, 

I have lot information in host_vars & group_vars folder, but Rundeck doesn't load it :/

Normal ?

**Comment by m4dm4rtig4n** [comment]
Hi

I solve my problem :)
=> Symlink /etc/ansible to my ansible install :+1:

**Comment by camaer** [comment]
We are having the same issue. When run manually using `ansible-playbook` the group_vars are loaded fine but when the same playbook is launched from rundeck they are not loaded properly. Our ansible path is already under `/etc/ansible`. Is there a way to make it work without a having to copy all the variables in the rundeck job ?

Here's how is our structure:
`
/etc/ansible/inventories/production/hosts
/etc/ansible/inventories/production/group_vars/*
`

Thanks
