### ISSUE TITLE
Issues gathering facts / creating nodes

### ISSUE THREAD

**Issue by afdevries** [rundeck-plugins/ansible-plugin#92]
I see the following task fail in service.log

Rundeck running under user rundeck. `rundeck` user has ssh access through key on `SN001` host.
Tried some variations for the resource model configuration with ansible plugin. But mostly kept it as straightforward as possible. 

ansible version : ansible 2.2.1.0
rundeck ansible plugin version : 2.0.2
rundeck version : 2.6.11-1
os : Ubuntu 14.04.5 LTS

Testing facts gathering on external host in shell:
`rundeck@rundeck001:~$ ansible all -m setup
SN001 | SUCCESS => {
    "ansible_facts": {
        "ansible_all_ipv4_addresses": [
            "10.31.100.34",
            "10.31.110.24"
        ], ...`

output from service.log when gathering facts for the one host configured in default /etc/ansible/hosts for ubuntu 14.04 through packages installed version.

`Using /etc/ansible/ansible.cfg as config file

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [SN001]

TASK [file] ********************************************************************
changed: [SN001 -> localhost] => {"changed": true, "gid": 0, "group": "root", "mode": "0755", "owner": "root", "path": "/tmp/rundeck/ansible-hosts648347803598887007/data", "size": 4096, "state": "directory", "uid": 0}

TASK [template] ****************************************************************
fatal: [SN001 -> localhost]: FAILED! => {"changed": true, "failed": true, "msg": "Source /root/.ansible/tmp/ansible-tmp-1485200138.97-274866329184452/source not found"}
        to retry, use: --limit @/tmp/rundeck/ansible-hosts648347803598887007/gather-hosts.retry

PLAY RECAP *********************************************************************
SN001               : ok=2    changed=1    unreachable=0    failed=1`

**Comment by MikeschTheCat** [comment]
I have the same Problem

**Comment by damageboy** [comment]
I'm seeing the same thing, I've opened a different issue for it before it (#95) before seeing yours...

**Comment by tangfeng123** [comment]
I have same issue with you

**Comment by DerekTBrown** [comment]
I think this issue has been fixed in a recent update, but feel free to reopen if the issue persists.
