### ISSUE TITLE
Print Formatted Messages 

### ISSUE THREAD

**Issue by ltamaster** [rundeck-plugins/ansible-plugin#93]
Hello,
Is there a way to print some nicely formatted messages using return vars from Ansible playbooks on the job summary page? instead of the usual Ansible output  (which is hardly readable for people not familiar with Ansible).

It would help greatly in the user experience.

Thanks

**Comment by DerekTBrown** [comment]
We have updated the project to default to normal verbosity, which should make it a little bit easier to read.  If you need still easier access, consider adding a workflow step to rundeck which prints the results using bash directly.
