### ISSUE TITLE
Ansible plugin options not displayed under rundeck's "Add Steps - Node Based"

### ISSUE THREAD

**Issue by rbgithuub** [rundeck-plugins/ansible-plugin#94]
I am using ansible plugin version "ansible-plugin-2.0.2.jar" for rundeck, after configuring the rundeck project with Ansible Node execution and Ansible File copy options I went-on to create a job in rundeck.

But under the "Add Step" option in rundeck, we normally have "Node Steps Plugins" and "WorkFlow Steps Plugins" 

By using this version ("ansible-plugin-2.0.2.jar") of ansible plugin I do not see the Ansible Module and Ansible Playbook plugins listed under "Node Steps" list of plugins, whereas it only gets displayed under the "WorkFlow Steps"

This was not the case with "ansible-plugin-1.3.2.jar".

Please help on this.

**Comment by DerekTBrown** [comment]
This is because this is an actual update to the behavior of the plugin.  It will only appear in the workflow steps.
