### ISSUE TITLE
Support for SSH key passphrases

### ISSUE THREAD

**Issue by bmaupin** [rundeck-plugins/ansible-plugin#96]
As far as I can tell there's no support for using SSH keys with passphrases. This would be nice to have.

Thanks!

**Comment by vshunkov** [comment]
Hi,

Also faced with same issue and looking forward for implementation "ansible-passphrase-storage-path" 

Thanks in advance!

**Comment by linuxmail** [comment]
hi,

we have the same issue. @DerekTBrown  Can we have some information, which parts (code) are important to have a look to create a patch request?  

cu denny

**Comment by frozenice** [comment]
hi @linuxmail 

I suggest looking at the appropriate plugin you want to enhance under [plugins](https://github.com/Batix/rundeck-ansible-plugin/tree/master/src/main/java/com/batix/rundeck/plugins) and work from there. Check out how the other parameters are implemented and how they get passed to Ansible.

**Comment by mcassaniti** [comment]
@linuxmail Do you need further feedback or is this issue OK to close?

**Comment by linuxmail** [comment]
hi, 

at the moment, all resources are blocked, so we can't develop the enhancement at this time. I hope, that we can do it next year. So Its Ok to close it for now.

**Comment by SecT0uch** [comment]
Hi, what's the status of this issue ?
I'm unable to configure passphrase to successfully add nodes:

- Added in Key storage: PrivKey and PassPhrase (as password)
- Configured Ansible node executor to use both
- Ansible Ressource Model doesn't offer to select Passphrase and my hosts are not appearing: Fails to connect
