### ISSUE TITLE
ansible log output verbose by default

### ISSUE THREAD

**Issue by linlinas** [rundeck-plugins/ansible-plugin#98]
Hi Guys,

I am running Rundeck with Ansible plugin and I found that every playbook execution is producing verbose (-v ansible option) output in Normal log mode.
Is this behavior correct or am I missing something?
A sample output you can see below.

12:26:32			PLAY [aut,pub] *****************************************************************
12:26:32			
12:26:32			TASK [setup] *******************************************************************
12:26:35			ok: [servername]
12:26:35			
12:26:35			TASK [set_fact] ****************************************************************
12:26:35			ok: [servername] => {"ansible_facts": {"var": 4001}, "changed": false}
12:26:35			
12:26:35			TASK [set_fact] ****************************************************************
12:26:35			skipping: [servername] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
12:26:35			
12:26:35			TASK [set_fact] ****************************************************************
12:26:35			skipping: [servername] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
12:26:35			
12:26:35			TASK [create threaddump] *******************************************************
12:26:37			changed: [servername] => (item=publish) => {"changed": true, "cmd": "aemcommand threaddump 'publish'", "delta": "0:00:00.640889", "end": "2017-02-23 12:26:37.302862", "item": "publish", "rc": 0, "start": "2017-02-23 12:26:36.661973", "stderr": "", "stdout": "Threaddump saved as /content/17.02.23-12.26.36-publish.jstack", "stdout_lines": ["Threaddump saved as /content/17.02.23-12.26.36-publish.jstack"], "warnings": []}

**Comment by javierurien** [comment]
+1 Is this configurable?

**Comment by linlinas** [comment]
Hello,

How hard would be to compile a new plugin version without verbose output ?
From what I see (and I am not a Java developer) in the code there is a one condition where verbose (-v) is chosen.
If we change this pice of code would it fix that issue?
https://github.com/Batix/rundeck-ansible-plugin/blob/master/src/main/java/com/batix/rundeck/core/AnsibleRunner.java

```
    if (debug == Boolean.TRUE) {
      procArgs.add("-vvvv");
    } else {
      procArgs.add("-v");
    }
```


BTW. is any one still working on that project or it has been abandoned ?

**Comment by frozenice** [comment]
Hi there,

compiling is not that hard, granted you have Java installed, as it uses the Gradle wrapper. Basically all you need to do is (taken from CONTRIBUTING.md):

> Build a new jar with gradle (run `gradlew jar`), it will be in `build/libs`

I don't know off the top of my hat, if that `-v` is needed for parsing some stuff, it might be.

As for the state of the project: I'm really sorry I can't invest much time at the moment, as there are other things, that need to be done, with higher priority. We don't use Rundeck + Ansible yet, so I'm kinda out of the loop.
That said, I'd really like to add more maintainers! This is not a closed governance project, the more the merrier. I created a [gitter channel](https://gitter.im/rundeck-ansible-plugin/Lobby) and added it to the README, to facilitate collaboration then.
If anyone would like to become a maintainer, give me a shout!

**Comment by linlinas** [comment]
Hi Guys,

@frozenice thanks a lot for a feedback. We have recompiled the package without mentioned pice of code and so far it is working for us.
Therefore it may be use as a workaround if anybody complains about verbose output in the Log Output.

**Comment by jacobamey** [comment]
So other than recompiling is there no other way? Recompiling makes me nervous, that and I'm now running with "Custome" code in production....

**Comment by DerekTBrown** [comment]
@jacobamey My tendency is to say that the current behavior is preferable to your PR as `-vvv` isn't as readable as `-v`.   Could you explain why you need the added verbosity be default? Why can't you just set the default job setting to `debug`?

**Comment by jacobamey** [comment]
@DerekTBrown I may have done something wrong there. But what I was looking for was no -v
by default. This causes too much output by default causing some logs to be a
100mb+ in size. I perform nightly restores using extrabackup.

I would rather there be no -v by default.

For debug I was saying -vvv would be fine as anything higher and we are
getting into ssh debug level. If you need more than three, in my opinion. 
it's time to go back to CLI.

Either way, my main request is to remove -v as the default output. It's too much
for a default. Also in its current format, we are stuck doing verbose no
matter what. If we leave it off I can always add it to my options when
building the play book out. More options seem better.

**Comment by jacobamey** [comment]
@linlinas FYI, this did get merged in today. Would expect it in the next release.

**Comment by jacobamey** [comment]
As of version 2.2.0 this is in place and working well :-)

![works-well](https://user-images.githubusercontent.com/3608280/29319095-bbdc7474-81a0-11e7-990c-dcd2ccdb8bc6.png)

**Comment by linlinas** [comment]
thanks a lot @jacobamey, I will test it today
